### ISSUE TITLE
SwissBorg - Quantitative Developer (Python) - Toronto

### ISSUE THREAD

**Issue by ankitml** [TechnologyMasters/jobs#101]
### Salary Expectation
* Full Time
* 85k - 120k CAD annually

### Location

- Toronto, Ontario
- Bay and Bloor, well connected with two subway lines

## What You'll Do _(Job Description)_

The ideal candidate  has > 2 years work experience with python, knows their way around full stack (frontend, backend, AWS infrastructure) and is very interested in  blockchain and cryptoassets. Having some machine learning, modelling  & simulations or financial industry experience will be preferred. 

## What You Need to Be Successful _(Skills)_

- Programming: You are experienced in Python. Some work in Scala in a plus, willingness to pick it up is a must.
- Datastores: We will be working with large data flow applications. Experience with Postgres/MySQL is a must, kafka, redis is a plus.
- Distributed Systems: You know how to design and build distributed systems, microservices and cloud architectures (preferably on AWS).
- DevOps: You have knowledge about running systems in production, monitor them and troubleshoot them if necessary.
- Code Quality: You are familiar with writing well tested & reusable code and add documentation where necessary.
- Ownership: You have a strong sense of ownership and entrepreneurial thinking - customer value should be your key driver.

## About SwissBorg

Swissborg is building the new era of wealth management on the blockchain. SwissBorg is headquartered in Lausanne, Switzerland and decentralized to the world with teams in Toronto, Tokyo and London. We recently completed our successful ICO and are now working hard to deliver on our  promises.

We are looking for developers for growing our quantitative research and development team in Downtown Toronto. If you like fast paced environments, using agile thinking, solving new challenges every day, in the rapidly growing  blockchain industry, you will love working with us. 

## What we offer 

- An energetic work environment with a high grade of autonomy and growth opportunities.
- Energetic work environment and multiple projects building trading tools, analytical tools, investment strategies research and experimenting with new technologies
- Very competitive Salary and Bonus
- Conveniently located at Bay and Bloor, near two subway lines.
- Free and unlimited drinks. (Coffee, loose leaf teas, draught beer)

## How to apply

Apply here : https://jobs.lever.co/swissborg/39262f67-c971-4d11-a758-fc316a474dd7

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by theetrain** [comment]
Hi @ankitml, I suggest modifying this sentence to be more inclusive 

> 2 years work experience with python, knows his way around full stack...

Try using **their** instead of **he**.

**Comment by ankitml** [comment]
Thanks @theetrain for pointing it out. My sincere apologies for this obvious mistake. 😞
