### ISSUE TITLE
Delphia - DevOps Engineer - Remote/Toronto

### ISSUE THREAD

**Issue by KevYuen** [TechnologyMasters/jobs#105]
### Salary Expectation

- $70-100k/year based on experience

### Benefits

- Extended Health Benefits

### Location

- Toronto, Ontario
- Remote OK

## What You'll Do
We are looking for a leader in the DevOps space, someone who can lead and guide our approach in building great software to help people make better decisions. In this role, you will need to balance between empowering others, execution, as well as contributing to the Delphia’s technical roadmap.

### Must Have

- Experience with AWS/GCP, Kubernetes, Docker 
- Terraform/Ansible or other similar tools
- Server monitor and network design
- System Security

### Nice to Have

- Data Science/Engineering Infrastructure experience
- VPN setup and management 
- Log Management
- Knowledge of Elasticsearch management

### Relevant Experiences

- Implementing security processes

## About Our company

Delphia (a recent Y Combinator graduate) builds artificially intelligent applications that help people make important life decisions and better understand themselves. Built by researchers and data scientists, our applications use computational social science and machine learning to provide highly personalized recommendations to users following a series of questions about themselves.

## How to apply

Please send an email to kevin (at) delphia.com with your resume, use ‘Tech Master - Devops Engineer’ as subject

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [x] Remote OK
- [x] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by theetrain** [comment]
Hi Kevin, please add a salary figure to increase the quality of your job post and candidate pool.

**Comment by KevYuen** [comment]
@theetrain This is really difficult for us, because we are open to candidates that can either lead the DevOps effort or someone that is more junior who can execute. We'd rather keep the posting open so we don't limit our candidate pool. 

If you have a suggestion on how we should do this. Please advice :)

**Comment by theetrain** [comment]
At that case, you can provide a salary range and be clear that you are seeking candidates at various levels. If the salary ranges depend on geographical location, be explicit about that as well.

**Comment by KevYuen** [comment]
@theetrain updated, thanks for the suggestion.
