### ISSUE TITLE
Weever Apps - Front End Web Developer - Hamilton, Ontario

### ISSUE THREAD

**Issue by TantienHime** [TechnologyMasters/jobs#113]
### Salary Expectation

- TBD
- Full Time

### Benefits

We put our teams first. A great team is given the autonomy and support to execute the plan and do their best work. We trust our teams.

In order to support you we offer:

- _A remote-friendly culture:_ Communication is key and we have several team members that are working remotely with us full and part time.
- _Training:_ Team members have access to a plethora of training materials, conferences, and we encourage pair-programming and mentor-ship.
- _Insurance:_ For our Canadian employees we have a good benefits package offering dental, drugs, and other kinds of coverage.
- _Vacations:_ Our team members must take them.
- _Mobile Phone Plan:_ Don’t worry about it, we pay for it.
- _Interesting Problems:_ Not all of the problems we encounter have frameworks or well-defined solutions. Own it and help us find the answers.

### Location

- Hamilton, Ontario
- Remote OK

## What You'll Do _(Job Description)_

The Frontend Developer will join our frontend development team. This person will be responsible for elements of function, user interaction features and usability improvements for each of our four products: “Forms Manager”, “Training Manager”, “Inspections” and “Process Manager”.

Day-to-day activities:

Work with our product team to implement frontend development of both new user interface (UI) features and core improvements to our platform, ranging from configuration improvements to the integration of charts and other libraries
Help us to improve our HTML5 / JS library performance and our specification-driven frontend programming patterns
Implement improved test coverage using libraries similar to Selenium and more
Engage in rapid cycle of design and iteration in collaboration with software engineers, marketing, and other stakeholders
Coordinate and provide input to our design team on product and engineering development

### Must Have

Please apply to join our team if at least three of the following apply to you:

- You have excellent communication and soft skills and care about user experience
- You enjoy working with Angular, Vue or other frontend Javascript libraries
- You understand the value of well written SASS/LESS and frontend templates
- You know how important good UI  “states” are and dive into that on any project
- You have some experience working with API’s and PostgreSQL or other database systems

### Nice to Have

Bonus points if:

- You have some knowledge in ARIA, copy writing, typography and aesthetics, motion design, material design language, UX/JTBD, style guides, Sketch, wireframes
- You know Haskell.  Wow.
- You have experience working in an Agile environment
- You are passionate about the problems we’re facing and have ideas on how to face them

### Application Process

Our hiring process consists of four steps:

1. Submit your resume, cover letter and a link to Github (or similar portfolio of your code) or send an email to jobs@weeverapps.com
2. Initial call
3. Technical Screen
4. Final Interview

We start with an initial call in order to answer any initial questions you may have about us and to discuss your experience. The technical screen can be completed either in-person or remotely at your leisure. We don’t want to take up much of your time!

The in-person screen is prescriptive: write some code to make a suite of tests pass and should take less than an hour. The take-home is less prescriptive and designed to be a small, short project to be completed at your own pace within a few hours at most (or more if you need it, there are no hard limitations).

We use the results of the technical screen as a barometer for the final interview. We don’t do any whiteboarding or other hazing rituals in the final interview. We only use the technical screen to cater the technical depth of the final interview to your skill level.

We’re pretty quick to follow up, potentially with an offer, within a day or two of the final interview.

We prefer candidates from all members of the community, including those from under-represented groups. If you have any requests or questions about our hiring practices we’d appreciate hearing from you. Please let us know if you have any special requirements to accommodate the situations of your application or employment with us.

## About Our company

Weever Apps is a growing software company based in Hamilton, Ontario Canada. We build cloud-based software products that large enterprises use to capture data, manage workflows, and access actionable reports. We replace clipboards and filing cabinets with tablets and databases and provide alerts, analysis charts, and other features that make data useful. We’ve been around for a while, but we are still flexible enough to make changes if it makes sense.

Our customers include:

Xerox
General Electric
Georgia-Pacific
Unilever
… and more! We tackle big problems with a small, focused team and powerful technology.

**When you join Weever Apps…**
You’ll be a valued member of a talented team who is dedicated to the success of the company. You will have a unique opportunity to grow and learn with a rapidly expanding company. We value the innovation, ownership and creative thinking of the staff in all departments and how that can improve the company as a whole. Make your mark at Weever Apps!

## How to apply

Send us your resume and cover letter by email to jobs@weeverapps, with the position in the subject line. In your cover letter, please mention the job for which you are applying and where you found this posting or who referred you to us so we can thank them.

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [x] Remote OK
- [x] Remote Regional
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by pocheptsov** [comment]
Salary label is irrelevant

**Comment by TantienHime** [comment]
@pocheptsov It is a salaried position, hence the tag. I asked about the amount/range from my superiors and they aren't sure what that will be yet, so I agree that the post doesn't meet the criteria, but it is a salaried position as opposed to an hourly rate. Is that what you were referring to?

**Comment by pocheptsov** [comment]
I see but still, it's a bit confusing in regards that you expected to see an amount cause using label hourly we can filter those posts, where all others should be salaried. Correct me if I wrong.

**Comment by TantienHime** [comment]
I was under the impression that the tag was simply to answer the question: "Is this a salaried position or hourly?" The question as to what the amount is was a different question. This was my understanding.

**Comment by ahmadnassri** [comment]
Correct, the current setup of tagging is automated, based on checking the "salary" box: https://github.com/TechnologyMasters/jobs/blob/3942f3287ead9aca460dce8ed0f27046b7275406/.varci.yml#L120

happy to take feedback and adjust this.

**Comment by theetrain** [comment]
@TantienHime is correct, the `salary` label represents a job post that is offering a salaried position, as defined here: https://github.com/TechnologyMasters/jobs#rate-of-pay

The reason we separate `salary` and `hourly` is to allow prospective job seekers to filter by their preference. 

@pocheptsov I could see how `full time` would imply `salary` in most cases, making the label unnecessary. We're happy to hear your thoughts on this. Feel free to open an issue in https://github.com/TechnologyMasters/ideas/issues regarding this labelling topic and we'll discuss further.

**Comment by ProfessorTom** [comment]
Is this position still open?

**Comment by TantienHime** [comment]
@ProfessorTom Apologies that I didn't see your comment sooner. We have closed this position, however, we're always looking for good people. We just finished hiring 3 people, but that doesn't mean we won't have more openings. Feel free to to reach out to me if this is still of interest.

**Comment by TantienHime** [comment]
This posting has now been filled.
