### ISSUE TITLE
Instacart - Senior Software Engineer - San Francisco

### ISSUE THREAD

**Issue by Eldwick** [TechnologyMasters/jobs#138]
## What You'll get

Instacart (YC S12) is building the best way for people everywhere in the world to shop for groceries. Using your phone or the web, you can order groceries and have them delivered to your door in minutes. You can choose from a variety of local stores, as well as being able to mix items from multiple stores into one order.

Every day, we solve incredibly hard problems to create an experience for our customers that is magical. We aim to give our customers back their invaluable time so they can spend it doing the things they love with the people they love.

The hiring process depends on the position, but will generally follow this flow: phone screen + simple challenge / take-home challenge / on-site. We're pretty flexible and can work with you on this.

We care that you can ship product and enjoy taking ownership over what you're working on. We don't really care where you went to school or what companies you've worked for.

Tech: • Ruby (on Rails) • ES6+ • React / Redux • PostgreSQL • Elasticsearch • Memcached / Redis

Data Analysis & Data Science: SQL, R, Python

Learn more about us and apply directly at: • https://careers.instacart.com/ • http://tech.instacart.com •

### Salary Expectation

- At or above SF industry standard salaries
- Full Time

### Benefits

- Talented and collaborative coworkers who will both push and support you
- Market competitive salary, equity
- Medical, dental, vision benefits and 401(k) retirement plan
- Take what you need vacation (and we really mean it)
- 16 weeks maternity leave / 8 weeks paternity leave so you can truly bond with your child
- Free lunch and dinner in the office; fully stocked kitchen and snack pantry
- Complimentary Instacart Express membership (free Instacart delivery!)

### Location

- San Francisco, CA
- Candidate may work from home for a few days every month 

## What You'll Do _(Job Description)_

We're looking for experienced engineers to join our fast moving team. We work on a range of interesting and challenging problems, from supporting thousands of concurrent shoppers and processing millions of data points in real time, to determining the best route for deliveries and predicting store inventory levels.

### Must Have

- Bachelor’s degree in Computer Science, computer engineering, electrical engineering or equivalent work experience
- Self-motivation and an enjoyment for a startup environment
- A blend of product, system, and people knowledge that lets you jump into a fast paced environment and contribute from day one
- Strong knowledge of common Web technology such as Ruby on Rails and/or Python and/or JavaScript frameworks (React, AngularJS, Ember or Backbone.js)
- An ability to balance a sense of urgency with shipping high quality and pragmatic solutions
- Extensive experience working with a large codebase and cross functional teams
- A strong sense of ownership

## How to apply

Reach out directly to me on slack @jamesjalandoni or email me james.jalandoni@instacart.com with your resume.

---

## Meta
- [ ] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by theetrain** [comment]
Hi @Eldwick, to make your job more searchable, please check off the appropriate labels under the 'Meta' heading.
