### ISSUE TITLE
Partnership with App Developers 

### ISSUE THREAD

**Issue by jonb153** [TechnologyMasters/jobs#144]
Grupee - App Developer - New York City

Salary:
Equity. 2% - 5%

Benefits:
None

Perks:
- Work your own schedule
- Choose your own custom setup

Location:
New York City, NY

What you will do:
Develop a Minimum Vial Product (MVP) for a social media platform. Nothing major in the UX/UI department but having experience with this is a must. I will need the front end and back end as well, but a bigger emphasis on the back end.

Skills:
iOS, Swift, coding, mobile development, UI, UX, back end, front end.

Must Have:
- 3+ years in mobile development 
- If you deployed apps of your own is a plus.

Relevant Experience:
- mobile technology
- up to date on current mobile trend

Who we are:
We are Grupee and we are new social media platform. We are looking into changing the dynamic on how we usually would interact on social media platforms. 

How to contact us:
Email will be the quickest way to reach us. Shoot your resume as well if you have one available. Subject should say “Grupee Applicant”.

Please send an email to:
Jon.bell@metroblack.us

- [ ] Full Time
- [ ] Part Time
- [x] Contract/Partnership
- [ ] Internship
- [ ] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by jonb153** [comment]
I know the details is a bit vague, but because of the nature of the business I was obliged to. If you contact me, I’ll be sure to explain more thoroughly what this project is about and the position you would be working on.

**Comment by lordexploisonmurder** [comment]
Hi! Please explain more thoroughly what this project is about. Also, it sounds like you're offering only 5% for what should be a co-founder role (easily 30%, probably halfsies, possibly more). 

You have this great idea, but building out a lightweight prototype that's fully functional is not only weeks of full time work, but will require constant engineering follow-through. If even moderately successful, you will NEED someone who will be committed to see it through.

Think of it this way: I'm going to be using many years of development experience (technically, a decade), making most of the product decisions on the fly (as is necessary in a tight working relationship with a non-technical co-founder), and generally building everything. What you will bring to the table are the skills I don't have.

When you're working on a project with someone else in this capacity, you have to sell THEM on YOUR pedigree. I invite you to post your resume here.

 The barrier to entry of being a CEO is incorporating.

**Comment by lordexploisonmurder** [comment]
Hi! Please explain more thoroughly what this project is about. Also, it sounds like you're offering only 5% for what should be a co-founder role (easily 30%, probably halfsies, possibly more). 

You have this great idea, but building out a lightweight prototype that's fully functional is not only weeks of full time work, but will require constant engineering follow-through. If even moderately successful, you will NEED someone who will be committed to see it through.

Think of it this way: I'm going to be using many years of development experience (technically, a decade), making many of the product decisions on the fly (as is necessary in a tight working relationship with a non-technical co-founder), and generally building everything. What you will bring to the table are the skills I don't have.

When you're working on a project with someone else in this capacity, you have to sell THEM on YOUR pedigree, and you need to bring value to the table. An idea is just an idea; without backing and research and a compelling story for its success, it's not even a good one. I invite you to post your resume here.

 The barrier to entry of being a CEO is incorporating.

**Comment by revmischa** [comment]
aahhahhahahahahahahhahhhhahahahahaaha loooooollll

**Comment by jonb153** [comment]
Mr. Murder, thank you for your input. I am glad you’ve seen through my deceptions. I am glad you actually took the time out of your day to expose my trickery. You are absolutely right. The worker (that would be you) with all the skills and knowledge should run most of the company and should earn most of the company too. In fact, the owner of the idea, the one who runs the business side of things (sole or with a team), the one who files for the company, the one has to keep the company from running to the ground, the one makes all the important decisions should MOST DEFINITELY own 5 percent of the company. Maybe less. That is exactly how all the biggest companies in the world run their businesses. If I may, I would like to suggest one last thing before taking my deceitful person to more viable candidates. Do your reserach before talking young Bill and for the love of God, please know your worth. 10 years plus in your career and you still struggling to make your big break. You just signed up on Github this past week and your first order of business is to bash the first post you see. I think we all can your bluff now...

**Comment by a-can-of-refreshe** [comment]
Hi! Looks like you didn't read what I wrote, or didn't understand it. So, I'll piece by piece break down the wall of text there and explain what I'm trying to say. 

First off, I'm not accusing you of trickery, I'm highlighting your naiveté in hopes that in the future you put more value on the people you're working with.

Second off, there is no company. You have no company. You have an idea, and an idea is worthless without execution and followthrough.

When you tell someone they'll get 5% in a 1:1 partnership, that is a miserable deal for what will be weeks (to months, and even years!) of hard work that in a major city earns you a salary and equity in a tco package ALWAYS north of $150k a year. You're not forming a partnership, you're bald-faced trying to fuck them. Take a look at examples of historical and modern startup equity among co-founders. https://wiki.epfl.ch/a3-angels/documents/reunions/a3angels07-herve_lebret-equity_split_study.pdf

Steve Jobs convinced Steve Wozniak to take something like 30% ownership in an early Apple. It's widely accepted that Wozniak got capital-f fucked by that. You are not Steve Jobs.

By the way, you are absolutely right that's exactly how "how all the biggest companies in the world run their businesses". Facebook employs around 25,000 people. How many do you have?

Next, there is no "owner" of an idea. It's an idea, unless you patent it, in which case you get about 15 years of protection (good luck patenting any variation on a social network, by the way!). There is execution of an idea. You, by yourself, are incapable of executing or else you'd be building it.

I made this account as a disposable account. I hope you can appreciate why. Call me a coward, but I don't care to taint my professional reputation. I see listings like this all the time and ignore them (as many other people do), but never as vague and boldly "I'm an idea guy" as this.

And yes, we have a term for people like you: idea guy. It's derisive.

**Comment by jonb153** [comment]
Honestly, I don’t even know why I entertain the narrow minded. If my post offended you than I beg of you to pardon my life. If you look closely at the post, under it I set out a disclaimer. I can give much detail on the post for a reason and you assuming that I don’t have a company shows the level of ignorance you have on the matter. If this post intrigues you and you want to at least know what is cooking behind the scene, contact me. My email is there. If not, find some other way to spend your time.

**Comment by a-can-of-refreshe** [comment]
Balking at compensation terms isn't narrow minded.
Give detail on the post.
I guess it's wrong to assume you haven't incorporated; but, I would not be surprised if you haven't.

Start off with some PRDs. Maybe a few slides showing a potential audience. Cometitor research.

Most important of all, post your resume.

**Comment by adamworrall** [comment]
This is not a job, this is a request for free work. should be closed.

**Comment by ahmadnassri** [comment]
I'm closing this issue.

the poster does not seem interested to offer fair compensation for the work expectation and we at TechMasters leadership will not encourage such postings.

please reach out to me directly if you have any concerns.

last, I will only add that ideas are worthless, the value is in the execution
