### ISSUE TITLE
Shoelace - Full-stack developer - Toronto

### ISSUE THREAD

**Issue by alexsloan** [TechnologyMasters/jobs#17]
### Salary Expectation

- $75k-$95k
- Full Time
- 0.1%-0.25%

### Benefits

* Complimentary coffee, fruit, snacks and breakfast in the office 
* Annual (maybe semi-annual :) company retreat 
* Flexible policies around core hours and working from home 
* Subway accessible office located in the St Lawrence Market area 
* Hammock, nerf guns and Sonos (coming soon) 
* Inclusive and diverse culture 
* Communal standing desk (still testing that one out)

### Location

* Toronto, Ontario

## Job Description

Shoelace is looking for a developer to join our team. In this role you’ll help evolve our product by continuing to automate our retargeting solution. As you get familiar with the code and product, you’ll increasingly be expected to take responsibility for coordinating and building full product initiatives. You’ll be working closely with our CEO who is also our head of product, the customer support team, and of course the rest of the small (but growing) dev team.

We're all learning every day and you should be excited about that. We expect you to quickly become a core part of the team, involved in long term product decisions.

Our current stack includes NodeJS, ES6, MongoDB, MSSQL, AWS, Docker, Redis, React, Angular, Mocha, Percy, CircleCI, and New Relic.

### Must Have

* Minimum two years experience with NodeJS/Javascript or solid skills in another language and the ability to learn new languages quickly
* Some experience with databases
* Understanding of the web stack and web app development in any language/toolset
* Experience planning and implementing product initiatives 

### Key Responsibilities

* Evolve existing product via data driven analysis
* Expand the automation of human expertise
* Help build the architecture that will allow us to scale 10x
* Work closely with customer success to automate the latest findings in retargeting
* Write and maintain testable code
* Leave the projects and code you work on in a better state than you found them
* Be self-driven, self-directed, and pragmatic
* Passionate about best practices and latest developments in the Javascript community
* Have a positive impact on company culture

## About Shoelace

Shoelace makes expertise accessible. Expertise continues to be one of the scarcest resources in the world. It's our view that this will not remain true for long and we are building towards this future by automating the role of a human expert.

Shoelace has over 1400 paying customers and growing rapidly. We have a fundamentally different approach to product design: Valuable software should work with minimal user input. This approach creates a ton of interesting technical and product challenges that we’d love to solve with you!

## How to apply

Find us on [AngelList](https://angel.co/shoelace-1/jobs/273020-full-stack-developer)

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary
- [x] Awesome

**Comment by 4534532** [comment]
skip this. Co-founder is is a certified prick!

**Comment by alexsloan** [comment]
Well that's not very nice. I'd ask that anyone inclined to believe this reaches out to someone on our team (you can find most of them on AngelList but I'll gladly send a list) and find out first hand what it's like to work at Shoelace. You'll also meet all three co-founders during interviews so you can check if any of us are "certified pricks".

**Comment by ahmadnassri** [comment]
@alexsloan I deleted the anonymous user comment, as it was not a productive nor constructive one. feel free to keep or update your comment as well.

**Comment by vcapretz** [comment]
hey @alexsloan do you offer visa sponsorship? I'm Brazilian and have no work permit or visas yet (just the tourist visa to US)

**Comment by alexsloan** [comment]
@vcapretz Hey, unfortunately not at the moment. Tbh, I wouldn't know where to begin with the overhead of a visa process and so that's not something we can currently take on.

**Comment by ruanltbg** [comment]
@alexsloan the application is only by AngelList? Or can be by email?

**Comment by alexsloan** [comment]
@ruanltbg prefer AngelList but doesn't really matter. If you want to email me, that's cool too. It's just alex at shoelace.
