### ISSUE TITLE
Mobcrush - Video Systems Engineer - Remote / Los Angeles

### ISSUE THREAD

**Issue by jgh-** [TechnologyMasters/jobs#176]
### Salary Expectation

- USD $140k+ (negotiable, DOE)

### Benefits

- Health insurance (if in USA)
- Potential relocation to Los Angeles

### Location

- Remote
- Los Angeles

## What You'll Do _(Job Description)_

We are looking for a video systems engineer who will be tasked with designing and implementing video systems components across our video stack on Linux, iOS, and Android.

## What You Need to Be Successful _(Skills)_

- Excellent problem solving skills
- Excellent debugging skills
- Not afraid to dig into difficult problems or learn new things

### Must Have

- Proficient with modern C++
- Experience with livestreaming protocols and formats (e.g. RTMP, HLS)
- Experience with networking and sockets
- Experience architecting systems

### Nice to Have

- Experience developing on iOS, Android, and Linux.
- Experience with various graphics APIs and mobile graphics is a big plus (OpenGL ES, Metal).
- Experience with cloud infrastructure, especially AWS.

## About Our company

Mobcrush is a live streaming app and community for gamers, powered by one touch mobile broadcasting. 

## How to apply

Please send an email to [james@mobcrush.com](james@mobcrush.com) with your resume

---

## Meta

- [X] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [X] Remote Worldwide
- [ ] Remote Regional
- [X] Remote OK

**Comment by mcsmithers** [comment]
Hi there!  I am local to LA, but love the option of location flexibility.  Is there an experience level in mind for this one?
