### ISSUE TITLE
IBM - Sr. ROR Backend Developer - Toronto

### ISSUE THREAD

**Issue by GraceFong** [TechnologyMasters/jobs#196]
### Salary Expectation

* $50+ /hr depending on experience - open to negotiation

### Benefits

* N/A

### Location

- Toronto, Ontario
- This is to be onsite located in the eastern part of Downtown. 
- Studio District

## What You'll Do _(Job Description)_

We need a senior RoR backend developer to be the backbone of our ERP software \
You will be doing a lot of the heavy lifting \
This begins as a 4 months contract that will likely extend further

### Must Have

-5+ years of experience with Ruby on Rails
-PostgreSQL
-Docker
-Git

### Nice to Have

- Database/visualization

## About Our company

Ample Organics is Canada’s most trusted technology provider for Licensed Producers. A complete ecosystem for cannabis businesses, our platform was designed for government regulations and makes compliance easy by tracking individual plants and reporting every detail of the growth, production, and sales processes. We are seeking courageous and intelligent people to join our team of trailblazers.

## How to apply

Please send an email to [grace.fong@experis.com] with your resume, use 'ROR developer' as subject

---

## Meta

- [ ] Full Time
- [ ] Part Time
- [X ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by cr03** [comment]
I'm confused, why wouldn't our community simply apply directly for this opportunity at https://ampleorganics.bamboohr.com/jobs/view.php?id=26 ?

**Comment by GraceFong** [comment]
> I'm confused, why wouldn't our community simply apply directly for this opportunity at https://ampleorganics.bamboohr.com/jobs/view.php?id=26 ?

Thank you for your question.
They are actively looking for contractors through IBM. 
The website would be a passive resume collector.
