### ISSUE TITLE
Digital Agency - Mid level .NET Developer - London

### ISSUE THREAD

**Issue by JawadS** [TechnologyMasters/jobs#197]
### Location

- London

## What You'll Do _(Job Description)_

Looking for a .Net Sitecore Engineer to join an ever growing team in the London office. 

With some exciting projects underway, this role would initially be focused on a large digital transformation project. Working alongside the Head of .Net, Technical Lead and BE Engineers you will be part of this exciting new project.

### Must Have

- Over 4 years experience and strong knowledge of C# .NET, MVC, SQL
- Knowledge of C# design patterns (SOLID principles)
- Working in Agile environments and understand agile processes
- Experience with GIT
- Sitecore Experience Management (DMS)
- Sitecore Experience Editor
- Build highly interactive, engaging digital experiences for our clients
- Maintain high standards of code quality, documentation, standards and security
- Succinctly communicate complex problems and proposed solutions
- Collaborate and communicate across teams, including design, experience planning, production, account management.

### Nice to Have

- Load Testing
- Sitecore Reporting, Analytics
- Sitecore DMS Personalisation
- TDS / Unicorn
- Fortis / GlassMapper
- Search Providers (Solr / Azure Search)
- CRMs (MS Dynamics / Salesforce)
- Experience of Agile methodologies

## How to apply

Please send an email to [jawad@cruits.uk](jawad@cruits.uk) with your resume, use 'Node Developer' as subject

---

## Meta

- [ ] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by theetrain** [comment]
Please put the company name in the title.
