### ISSUE TITLE
Mid-Level Software Engineer

### ISSUE THREAD

**Issue by eshields3591** [TechnologyMasters/jobs#205]
### Salary Expectation

- Market Rate - Negotiable
- Full Time

### Benefits

- Medical, Dental Vision
- 401K matching up to 4%
- Remote days available
- Nice office in Hudson Yards!
- ...

### Location

- New York, New York

## What You'll Do _(Job Description)_

As a Software Engineer, you’ll join our development team as a full contributing member, building new features, maintaining our existing codebase, and solving all sorts of technical problems. We build everything from tools for our internal sales and management teams to external applications for our day-to-day customers. Whether you’re building a new responsive UI component, optimizing a particularly nasty API call, or designing a database schema, you’ll be empowered to build it the right way, and because we’re a small team, everything we do has a big impact on the way we operate. We’ve got applications written in Java, Scala, and C#, and though we favor Scala and Angular for new applications, we’re always open to picking the right tool for the job.
 

### Must Have

- 2+ years of experience working on enterprise level applications
- Experience with Java, Scala, C#
- Experience working with relational databases
- Git
- Experience with some automated build tool (Maven, SBT, Travis)

### Nice to Have

- Scala
- Angular

### Relevant Experiences

- E-Commerce

## About Our company

 
H.Bloom is a national leader in luxury floral and plant corporate services specializing in the high end retail and hospitality industries. With the help of our team of highly skilled Account Executives and our curated network of floral shops we are able to offer customized services to a prestigious portfolio of well recognized brands such as rag & bone, Omega, Microsoft, SoulCycle, DryBar, and many more. H.Bloom products are also available for delivery nationwide from our online web-shop so our beautiful designs can also be gifted or enjoyed at home. (www.hbloom.com/gifts)

H.Bloom was launched in April 2010 and acquired by From You Flowers, part of Tenth Avenue Holdings, in March 2016. H.Bloom has been fortunate to receive coverage about our luxury service and sophisticated business model in many well known publications such as The New York Times, Business Insider and The Wall Street Journal.
We are growing fast and are looking for folks who are passionate, innovative, fearless, and adaptable. H.Bloom offers a startup culture and flexible work schedule where employees have the opportunity to make an impact among a growing team of energetic people who work hard, love what they do, and help each other through collaboration.

## How to apply

Please send an email to Eshields@tenthavenuecommerce.com. I am the direct hiring manager and you will be contacted for an interview! Please also remember to include your resume.

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by theetrain** [comment]
The company name and location needs to be in the job post title.
