### ISSUE TITLE
Salesforce Development Manager- Chicago

### ISSUE THREAD

**Issue by marquita916** [TechnologyMasters/jobs#22]
The Salesforce Development Manager, will lead a team of highly effective engineers as they work with our internal IT teams and customers to support their demands and help them to meet their business goals and objectives.  The Salesforce Development Manager  works under general direction of a director.
 
Responsibilities:

 
Foster an environment that encourages quality, productivity, creativity and innovation
Lead, manage, coach, mentor and strive to continually improve team efficiency and effectiveness
Facilitate team stand-ups, review meetings, prioritize team work, and act as functional manager
Provide technical mentoring and leadership
Plan and ensure sufficient labor resource capacity and capability are available to meet the business forecast (short and long) for software engineering
Lead SCRUM, Agile and Waterfall software development processes
Design, build, and enhance applications and, integrations with a focus on flexibility, scalability, security, performance, quality and utilizing industry best practices. 
Troubleshoot complex issues and improve application system performance by responding to client specific problems and fixing defects; employ methods such as smoke testing to additionally validate product quality before involving other team members or clients
Define and maintain team operating standards for items such as SDLC processes, coding standards, code control, issue tracking, time reporting, to improve productivity, velocity and quality
Support, enhance, and maintain existing systems by analyzing existing code, identifying areas for modification and correcting software defects
Ability to translate and document customer requirements into specifications including complex business processes and document using the appropriate tools 
Drive continuous improvement in design quality and delivery through the use of metrics
Implement and managing the application lifecycle management process for code through development, test, and production environments
Actively participate in the day-to-day engineering projects and activities
Maintain currency with development best practices/trends 
Keep close partnership with other team members by adequately transferring knowledge and collaborating
May be required to handle technical support calls, as needed, during the year to support customizations, custom code and applications

Minimum Qualifications:
 
Masters/Bachelors degree in Computer Science, Software Engineering, or Equivalent
4+ years leadership in a similar role, managing 3-5 software engineers and working with cross functional teams that have varying levels of technical acumen. 
8+ years in the Software Engineering Discipline , including advanced hands-on experience using Latest Programming Languages, Object-Oriented Programming, High-Performance, Fault-tolerant Distributed Systems, Data Storage Systems
Excellent communication skills and the ability to interact professionally with executives, managers, and subject matter experts with a demonstrated ability to work in a team-oriented and service-driven environment
Ability to drive a project through the full development lifecycle
Strong knowledge of software development methodologies and best practices
Experience leading teams using Agile/Waterfall development methodologies 
Strong orientation to detail, process and prioritization
Ability to multitask, and propensity to handle interrupts with poise and professionalism while meeting timelines
Experience with Managed Packages and integrations to other 3rd party solutions
Project management skills, including requirements gathering, working with cross functional teams, capacity planning and providing accurate time estimates
 
Preferred Qualifications:
 
Prior ScrumMaster
5 years working in designing, developing and architecting enterprise software using Salesforce.com and advanced programming using C++, C#, Java
4 years Platform development with a broad knowledge of customer application development, using the right mix of declarative and programmatic capabilities to create custom applications
Experience with front-end testing frameworks (Selenium, Jasmine, etc) 
Data Warehouse support
Experience using SOQL, Salesforce record indexing, integration of web services using SOAP and REST API’s
Expertise with database software such as DevOps Experience and managing operating systems such as Windows Sever 2008/2012 or Linux and database software such as Microsoft SQL Server 2008 or 2012
Salesforce Platform Developer I certification or ability to obtain within 3 months of hire

**Comment by ahmadnassri** [comment]
Plase follow the provided template!
