### ISSUE TITLE
Senior Service Reliability Engineer (SRE)

### ISSUE THREAD

**Issue by cr03** [TechnologyMasters/jobs#233]
### Salary Expectation

- Excellent pay, commensurate with experience
- Contract (US-denominated) or Full Time (Canada or US)

### Benefits

- Health & Dental
- Paid Vacation for FTE

### Location

Company is based in Oakland, CA but the vast majority of our company works remotely.

We are currently only hiring full time and contract candidates who are located in the United States and Canada.

## What You'll Do _(Job Description)_

Get started quickly to help us with hands-on tactical support for immediate and ongoing infrastructure challenges
Assist with the evolution of our highly available stateful storage systems
Champion a cloud-native and declarative approach to infrastructure
Make pragmatic decisions with the business in mind
Foster a culture of automating everything

### Must Have

- Experience with medium or large scale infrastructure
- Experience with application and infrastructure observability
- Experience with fully managed and serverless infrastructure
- Strong AWS experience, including AWS Lambda and RDS
- GCP experience
- Strong containerization experience
- Strong Hashicorp Terraform or infrastructure-as-code experience
- Observability platforms experience, such as Stackdriver, Splunk, New Relic, Elastic Stack, Prometheus, Grafana, Jaeger, etc
- CI platforms experience, such as Github Actions, CircleCI, Travis or GitlabCI

### Nice to Have

- CouchDB experience a huge plus
- Legacy virtual machine management experience
- Identity Provider experience, Okta, Auth0, etc
- Hashicorp Vault experience
- Ansible experience a plus
- Azure experience a plus
- CD platforms experience a plus, such as Spinnaker
- Nginx and HAProxy experience a plus
- Postgres or other relational database experience a plus
- Redis experience a plus

### Relevant Experiences

- You've likely read: The Phoenix Project, The DevOps Handbook, and The SRE Book.

## About Our company

npm is the world’s largest software repository, with over 10 million users and over 40 billion software package downloads every month. Our systems are critical to software engineers all over the world and used in every industry; from the public registry, which serves packages to open source engineers and small organizations, to our new enterprise solution, which provides single tenant registries for medium and large customers.

## How to apply

https://jobs.lever.co/npm/c29054aa-8909-4855-a009-42a83b42724a

---

## Meta

2
- [x] Full Time
- [ ] Part Time
- [x] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [x] Remote Regional
- [x] Remote OK

**Comment by eddyaman** [comment]
Hey Ian, would npm be interested in sponsoring the right candidate?

Thanks and best regards,
Aman

**Comment by cr03** [comment]
Bump because we actually still have an opening.
