### ISSUE TITLE
Contino - Sr. DevOps Engineer - New York, NY

### ISSUE THREAD

**Issue by maydin3** [TechnologyMasters/jobs#24]
[Contino - DevOps Engineer.docx](https://github.com/TechnologyMasters/jobs/files/1359448/Contino.-.DevOps.Engineer.docx)

**Comment by maydin3** [comment]
## What You'll get
The Senior DevOps Consultant will work internally at our client sites with team members to engineer and architect solutions, as well as coaching and mentoring DevOps principles and practices. The DevOps Engineer will work alongside Principal level Engineers and Account Principals.

### Salary Expectation

- Dependent upon experience, $125k-$160k Base
- Full Time

### Benefits

- 100% company paid benefits for individual and/or family 
- 3 week PTO along w/ federal bank holidays, unlimited sick and personal days, flexible WFH
- new laptop/macbook/tablet of your choice
- $75/month for cell phone reimbursement
-  Company paid life insurance, LT/ST disability 
-  401k plan
-  Equity after a year of employment, if eligible

### Location

- East Coast willing to travel to client sites primarily around NY,NJ,PA,MA

## What You'll Do _(Job Description)_

As our DevOps experts, you would be leading engagements for Contino on client site. This would involve leading our Contino team on the project and stakeholder management from the client side. We work in a way where we would also assist with upskilling the client teams and finishing the project with the client having more knowledge of processes, ‘DevOps’, cloud, containers etc.

## What You Need to Be Successful _(Skills)_
•	Experience of working within a DevOps environment
•	Experience of the full software delivery lifecycle
•	A keen interest in technology
•	A good attitude and mindset
•	Keen interest in other methods of working such as Agile for example
•	Systems or software engineering background
•	Good experience with scripting, Linux, automation, cloud, monitoring etc
•	Building CI/CD pipelines
•	Solid technical background/understanding in DevOps, Software Engineering or Infrastructure Engineering so that you're able to understand high level technical briefs, talks and ideas.
•	Deep understanding and exposure to DevOps and able to communicate on what it is, where and how its used and how it has progressed over time.
•	Up to date with technological advancements in the software engineering space and/or DevOps space.
•	Client facing and client management experience (consultancy background ideally, but not essential)
•	Strong communicator in the English language at both a technical and non-technical capacity.

### Must Have

- 3+ years working within a DevOps environment
- 3+ years of solid technical background/understanding in DevOps, Software Engineering or Infrastructure Engineering 

### Nice to Have

- Docker
- Kubernetes
- AWS
- Terraform
- Ansible
- Azure

### Relevant Experiences

- Systems Engineering
- Infrastructure Engineering within DevOps culture

## About Our company

Due to rapid growth and increased demand for our world class services, we are looking for multiple Technical leaders to help build our US market share by driving the world's leading enterprise organizations in adopting DevOps. We are heavily engaged across multiple household names in the financial services, telecoms, retail and eCommerce industries in helping them deliver software quicker and innovating at pace. This is an excellent opportunity to join a global technical team, working with some of best and most passionate engineers while also developing your skills and directing your career. We have a high standard of work and our bar is set high with engineering/consultant teams.

## How to apply

Please send an email to [melissa.aydin@contino.io](email@email.com) with your resume, use 'Sr. DevOps Engineer' as subject

---

## Meta

- [X] Full Time
- [ ] Part Time
- [X] Contract
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [X] Salary

**Comment by theetrain** [comment]
Create a new issue, please. The content of a job posting cannot be parsed by our automation tools unless it's in the first comment.
