### ISSUE TITLE
Jobber - Senior SRE - Toronto or Edmonton

### ISSUE THREAD

**Issue by MattBelanger** [TechnologyMasters/jobs#248]
### Salary Expectation

- Starting at 90k, negotiable and depending on location
- Full Time

### Benefits

- A total compensation package that includes an extended health benefits package with fully paid premiums, RRSP matching, and stock options.
- A dedicated Learning and Development function to help you reach your career goals and fullest potential.
- Three weeks paid vacation for your long breaks and a fully stocked kitchen for your short breaks.

### Location

- Toronto, Ontario or Edmonton, Alberta
- Work from home for particular circumstances, expectation is generally to be in office

## What You'll Do _(Job Description)_

Reporting to a Senior Development Manager, the Senior SRE will join a team of Engineers who are working to scale Jobber’s application to meet our aggressive growth targets, accelerate our product development teams, and operate our application at a high level. 

Today, our application is hosted on a mix of Heroku and AWS. We are currently exploring the next stage of our infrastructure, and the successful candidate will help us shape that vision. 

The Senior Systems Reliability Engineer (SRE) will:

- Help design, implement, operate and maintain our infrastructure with Infrastructure as Code. Includes advising on build vs buy decisions.
- Advocate for SRE principles and practices across the Product Development organization, and help us build a DevOps culture.
- Participate in our on-call rotation, and help improve the on-call experience.

## What You Need to Be Successful _(Skills)_

- 2-3 years working as an SRE or similar role, and 5 or more years as a software developer, sysadmin, or similar.
- Understand the culture of DevOps, and worked in a successful DevOps environment
- Experience with AWS, or another modern Cloud platform.
- Strong communication and collaboration skills.
- Strong knowledge of Terraform, CloudFormation, or other Infrastructure as Code languages.

### Must Have

_See Above_

### Nice to Have

- Experience operating Web-based SaaS software
- Understand how to scale a service
- Cloud migration experience

## About Our company

Jobber exists to help people in small businesses be successful. As featured in the Globe and Mail, we work with home and field service companies to help them better quote, schedule, invoice and collect payments from their customers. We’ve come a long way from our first customer in 2011 and have just scratched the surface of what we want to accomplish for our customers.   

## How to apply

Please visit our website to apply: https://getjobber.com/careers/senior-systems-reliability-engineer-sre-4423784002

---

## Meta

- [ X] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by eddyaman** [comment]
Hey Matt,
Would Jobber be open to sponser an international candidate from New Zealand?
Thanks
