### ISSUE TITLE
Konrad Group - Multiple Development Positions - Toronto, ON

### ISSUE THREAD

**Issue by afieldKG** [TechnologyMasters/jobs#255]
[Konrad Group](https://www.konrad.com)

### Benefits
- provided equipment (laptop, monitor, keyboard, mouse, etc.)
- pool table, video games, ping pong tables
- monthly socials
- monthly team events
- retreats, ski trips, boat cruises
- friday lunches

### Location
Toronto, Ontario
Candidate works on-site

## What You'll Do
We are looking for multiple positions, please checkout the job descriptions here!
Looking especially for Mobile Developers!!
[Konrad Careers](https://www.konrad.com/careers)

## How to apply
Please DM me with some information about yourself, and any questions you have.
We can discuss the process from there!!

If you don't have any questions and want to go straight through the site, checkout the careers page listed above and select the position you're interested in. There are multiple options on the right on the way to apply.

---

## Meta
- [x] Full Time

**Comment by nikkiwu** [comment]
Hey @afieldKG 

What's the best way to contact you?  I would love to speak about possible opportunities at Konrad. 

Cheers,

Nikki Wu
