### ISSUE TITLE
Liberty Mutual - Senior Software Developer - Indianapolis IN

### ISSUE THREAD

**Issue by onezeroonezerooneone** [TechnologyMasters/jobs#28]
Please see the full details below.  Thanks!

https://lmig.taleo.net/careersection/lmigcorp/jobdetail.ftl?job=89680

**Comment by theetrain** [comment]
Job postings need to follow the provided template. Please try again without deleting every header. https://github.com/TechnologyMasters/jobs/blob/master/.github/issue_template.md

**Comment by onezeroonezerooneone** [comment]
Hi theetrain, I was just about to edit in that information, but I will open a new issue now.  Thanks.
