### ISSUE TITLE
Artery - Full Stack Engineer - Toronto

### ISSUE THREAD

**Issue by zachgoldstein** [TechnologyMasters/jobs#285]
## About the Role

We’re expanding our core technical team to build out critical systems throughout the product. We are looking to hire strong generalist engineers with a frontend focus who can contribute across multiple technical domains.

You’ll work with a great technical team to build out all areas of the platform. The community Artery fosters is a wonderfully eclectic group of artists, performers and generally fascinating people. The work we do empowers people to come together in real life every day, so we feel it's particularly rewarding.

If this piques your interest, definitely get in touch. We'd love to hear from you!

## Daily Experience

- We are seeking people who are comfortable with constant iteration and creative problem solving. This means we're often trying to do more with less, so a strong candidate has the ability to find simple solutions that can be iterated on over time.
- Our stack involves a JS heavy SPA interacting with a Golang backend. Features often touch both sides of the stack. You'll be regularly exercising a broad set of skills to deploy features.
- Generally features involve more moving pieces on the frontend and require a particular interest in frontend engineering. Solid understanding of JS principles would a big asset.
- We strive to regularly improve the codebase across all levels of the stack. The code has gone through a number of evolutions, so we attempt to set a healthy pace that involves tackling technical debt.

## About You

- Have experience defining, building and shipping software to a sizable number of people.
- Have a broad technical background with a particular focus on frontend engineering.
- Have a bias towards taking action and attempt to move forward when uncertain.
- Are comfortable on a small team where collaboration and leadership are critical.
- Love writing quality code and leaving the code base better than how you found it.
- We have our eye towards a future mobile app (likely a hybrid), so experience around the mobile development cycle is nice to have.
- Are thoughtful about tasks at hand and look to identify technical bottlenecks early.
- Are excited about community building and providing tools for people to self-organize cultural experiences.

## What’s in it for you?

You will be creating scalable social infrastructure for artists, communities and cities around the world.

- Our team is supportive, diverse and passionate. As an early stage product, the potential for leadership and growth is limitless.
- A culture of values-driven technology.
- Competitive salary, flexible hours and meaningful equity (stock options).
- Behind the scenes access to every Artery showcase - in Toronto & around the world.

### Salary Expectation

- 70k-110k CAD

### Location

- Toronto, Ontario, Canada
- Flexibility to work from home as needed

## How to apply

Apply at https://artery.typeform.com/to/UrbeG2

## Meta

- [x] Full Time

![DSC_5546-2](https://user-images.githubusercontent.com/1009156/73310050-7be8ce80-41f1-11ea-81b0-8b4ee982702a.jpg)

**Comment by alexkayabula** [comment]
Hello @zachgoldstein, I am interested in this role. Just sent my resume. Hope to hear from you soon.
