### ISSUE TITLE
Coorva - Full-stack Engineer (React, Node.js) - US citizens only

### ISSUE THREAD

**Issue by Augusto-Castillo** [TechnologyMasters/jobs#286]
[Coorva] -[Full-stack Engineer (React, Node.js)] - [Windsor Mill, MD]

$120-140k Salary Expectation

- Contract / Full Time

Benefits
- Competitive base salary
- Three weeks of PTO
- Ten paid holiday days
- Comprehensive health benefits (medical with HSA option, dental, and vision)
- Professional development and training reimbursement
- 401k retirement plan with matching benefit
- 100% paid short-term and long-term disability
- 100% paid life insurance
- Flexible Spending Accounts (FSA)
- Casual working environment
- Flexible working hours

Location: Windsor Mill, MD

The Client is looking for a full-stack engineer to help us build modern digital health services. The project involves implementing highly interactive and modern web interfaces with React that will be used by healthcare providers across the country. The system is backed by Node business services implemented in a microservices paradigm. Some of these services will be exposed for public consumption and some are used for enterprise integration. The system will support upwards of tens of thousands of concurrent users. The project will be implemented using an Agile, Scrum-based process that includes Sprint Planning/Review/Retrospectives and daily stand-ups. The team uses human-centered design to implement highly modern, usable interfaces.

Must Have

- Experience developing front-end web user interfaces with React is required.
- Minimum 3 years experience developing front-end web user interfaces with React
- Experience with designing RESTful backend microservices and developing them using Node.js and Express
- Experience with database integration, relational (PostgreSQL) preferred. NoSQL (MongoDB) a plus
- Experience with SASS/SCSS or css-in-js type approaches for stylesheets highly preferred
- Experience with with Jekyll or other static site generators a plus
- Experience with AWS and Docker highly preferred
- Experience with build tools like webpack, npm, and gulp/grunt
- Experience with Test-Driven Development using automated testing frameworks such as Jest, Sinon, and Enzyme
- Experience ensuring your code builds and deploys properly through Continuous Integration/Continuous Deployment processes built in Jenkins
- Expertise working as part of a dynamic, interactive Agile team developing and delivering digital services
- Ability to work with and coordinate with other developers using digital tools such as Slack Experience with version control tools, such as Git
- Knowledge of modern design patterns and building enterprise-grade production applications
- Excellent command of written and spoken English

About our Company

Coorva is a software development company that makes custom-made web platforms and mobile apps for our clients

## How to apply

Click on the link below:

https://www.coorva.com/jobs/full-stack-engineer-react-nodejs-2020-01-30-151551067917/

- [X] Full Time
- [ ] Part Time
- [X] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [X] Remote Regional
- [ ] Remote OK

**Comment by kspaans** [comment]
I just talked with the hiring manager, and role is still available!
