### ISSUE TITLE
MakeIT - VP of Business Development - Remote 

### ISSUE THREAD

**Issue by EddieErkinbekov** [TechnologyMasters/jobs#298]
### Salary Expectation
Through an international team, we can offer extremely competitive prices for junior and senior developers who have comparable costs to permanent developers across Europe and the USA & Canada. However, you only pay for hours actually worked, no vacation, no compensation in the event of illness-related absence. -> Perfect for startups, first MVPs, tests, to support the existing team or for unsafe projects.

### Benefits
For the entire term of the customer relationship, there is payment after each customer invoice paid.
A share is paid for every hour sold.
There is a staggering: the more hours sold, the more shares per hour for you.

### Location
Complete Remote, worldwide

## Concept
The customer is provided with his own project manager who takes care of the development of the product/service.
After onboarding, a roadmap is developed for the customer, which is then discussed together. After that, the projects are worked on according to SCRUM in normal sprint cycles of 2 weeks. There are two internal QA cycles before each release: first by another developer or dedicated tester and then also by the project manager.
Unit & integration tests can be set upon request.

## What You Need to Be Successful _(Skills)_
English communication -> Since we are currently mainly working with the UK, US, UAE and Israel, there are currently only English-speaking project managers, which will of course change if the order situation increases.
* Project sizes from 2 developers sold per month (i.e. no projects such as theme adjustments, plug-ins for WordPress, etc.)
* There must be experience with IT projects (so that problems of the customer as well as the scope of a project can be better understood).
* Experience with selling IT outsourcing would be optimal.
* Freelance work: Therefore, invoices have to be made for the commissions

## About Our company
We are a top development agency from Ukraine with 25+ inhouse developers who deliver successful products.

## How to apply

Please send an email to [adilet@makeit.technology](adilet@makeit.technology) with your resume, use 'Business Developer' as subject

---

## Meta

- [ ] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by kspaans** [comment]
Closing because this is promoting an agency, not advertising a job opening.
