### ISSUE TITLE
QuickTapSurvey - Product Design / UI / UX Designer - Toronto, Canada

### ISSUE THREAD

**Issue by theetrain** [TechnologyMasters/jobs#3]
### Salary Expectation

- Based on skills and experience

### Benefits

- Catered breakfast every Friday
- Health benefits
- Unlimited snacks
- Hack day competitions
- Beer-o-clock Fridays
- Education & Training
- Gym membership
- Slack

### Location

- Toronto, Ontario
- Preference is to work onsite 

## About Our company

Our vision is to be the world's leading in-person survey platform. We're always looking for smart, passionate and motivated people to join our quickly growing team in Toronto, Canada. Being a small company, you'll be given the opportunity to grow your career quickly and take on as much as you can handle!

## How to apply

https://quicktapsurvey.bamboohr.com/jobs/view.php?id=33
@warrent-github
Originally posted by slack user `@warrentom`

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [x] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by warrent-github** [comment]
@theetrain you may delete this, thanks!

**Comment by theetrain** [comment]
Duplicate of #8
