### ISSUE TITLE
Senior Back-End Developer -PHP-100% Remote 

### ISSUE THREAD

**Issue by aliyalazarus** [TechnologyMasters/jobs#303]
My client is looking for a passionate individual to join their team as a back-end developer. This is a full-time position. The development team works remotely (from home) using video and other solutions for daily communication. Very rewarding work environment with a team that is passionate about learning and delivering great software products.

As a Senior back-end developer, you'll work with primarily with PHP to deliver enhancements and new features for their consumer and dealership facing applications, enabling dealerships to engage and communicate with car shoppers. There will be opportunities work with other technologies such as NodeJS, HTML/CSS/JQuery, and several data stores including MySQL and Redis. Their system is high-load providing challenging problems requiring creative solutions in a professional high-load environment. They have multiple applications that comprise our system including both desktop and mobile applications.

What they would like to see:
· 7+ years experience with PHP
· 4+ years experience with front-end Javascript and jQuery
· Up-to-date knowledge of modern HTML, CSS and JS
· Experience building and interfacing with RESTful APIs
· Strong personal and communication skills
· Experience with MySQL and Git
· Experience with some modern PHP frameworks (e.g. Zend, Laravel, CakePHP,
Symfony)
· Experience with writing tests
· Additional nice-to-haves: Redis, web sockets, NodeJS, Amazon AWS/RDS, React

Salary is anywhere from 120-160K CAD DOE. If interested, send a copy of your resume to aliya.lazarus@jobspringpartners.com.

**Comment by tojorodialson** [comment]
thank you
