### ISSUE TITLE
 Perly Consulting - Software Analyst - Remote/Toronto

### ISSUE THREAD

**Issue by CourtneyZorio** [TechnologyMasters/jobs#308]
## What You'll get
We are hiring a Software Analyst to join our experienced team of business consultants that help businesses scale. The role will start of primarily being focused on our government stimulus services (acquiring R&D funding for our clients from the government), and will open up doors in the near future to transition to a role focused on helping our clients scale through automation and process improvement. 

### Salary Expectation

- $60 000 - $90 000/year, based on experience. (The duties of this position are adjusted based on your ability level, you are paid accordingly)
- Contract / Full Time

### Benefits

- Work with a completely remote company with a high degree of autonomy and amazing team cohesion. 
- Be a part of a dedicated learning culture, passionate about continuous individual growth. We invest in our people. 
- Get paid to learn about great technology being built at the forefront of leading industries.
- Opportunity for lateral career growth if you are interested in opening up new doors. (We are very interested in individuals with a passion for automation). 
- Work with an experienced team with a track record of excellence. 
- As a 100% remote company, you can work from anywhere in the world. 

### Location

- Fully remote, you can work from anywhere in the world. Most of our team is based in Toronto. 

## What You'll Do _(Job Description)_

As a software analyst, you will be primarily focused on working directly with our clients to identify potential projects and claims for funding. You will interview client business and engineering teams to extract all the detailed information regarding their R&D, and filter it to determine what is applicable and what is not. You will structure the claims yourself based on their qualification efforts and prepare a submission on behalf of the client. Not only do you perform the work, you also manage the relationship with the client and be their sole point of contact.

In addition you will be leading automation projects aimed at improving the efficiency of our client’s technical processes and business operations. 

This role is full time, although exceptions can be made for part time/contract work if you are exceptional. 

### Must Have

- You have relevant software education (i.e Computer Science) or relevant work experience within the software industry. 
- You have great writing skills and the ability to process complicated information succinctly. 
- Excellent project planning and verbal communications skills. Adept at prioritizing and managing multiple assignments

### Nice to Have

- (Preferred) You have experience, education or a deep interest in automation, Six Sigma, LEAN, etc

### Relevant Experiences

- You have previously held a position in a technical field where you were responsible for the management of people, processes or projects. 

## About Our company

Perly Consulting is a high growth professional services business that works with leading technology companies in Canada to help them scale by improving their business processes with automation and acquiring government funding for R&D projects. 

We work closely with our clients to identify process improvement options, as well as opportunities for gaining government funding for their R&D projects. We own the entire process, from analyzing clients' engineering innovations to organizing R&D claims for submission, all while coaching our clients on the most efficient and productive methods to use for maximizing their business potential.

We are a small team led by experienced leaders and we are growing! Our company is focused on intense growth and learning, and we invest heavily in developing our team members. We operate with a completely flat structure; there are no managers here. 

## How to apply

Please send an email to czorio@gardnerwalker.com with your resume, use 'Software Analyst' as subject

---

## Meta
- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [x] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by vrindajain** [comment]
Hello, I'm Vrinda, I was trying to apply for the position today. But unfortunately, it shows the mail delivery status failure. Can you help me with that?
