### ISSUE TITLE
Coalition's Engineering Organization is Growing!

### ISSUE THREAD

**Issue by dannycatalano** [TechnologyMasters/jobs#354]
We're the fastest growing and best capitalized provider of cyber and technical insurance. We actively scan our 25K+ global customers and warn them of problems to ensure that they don’t need to make claims in the first place. Win-win. 

Our remote-first Engineering team is growing a lot this year - from Core Platform to Customer Security and Data Science. Only in the US, Canada, and Portugal at this time. Our stack is currently oriented around Flask with a smattering of Go micro-services. The glue holding it all together is a combination of REST and SQS queuing (some legacy Rabbit stuff in there too).

Check us out [here](https://jobs.lever.co/coalitioninc)

Ready to solve cyber risk? Feel free to apply, or DM me. Know someone who may be interested? Tag them to this thread!

**Comment by rmc3408** [comment]
Hello Danny Catalano,

I have 2 years of hands on experience in software development and extracurricular projects using React.js. On the Coalition website, there is a FrontEnd position. Are you accepting new Grads? 

I have just graduated from Centennial College in Toronto (GPA 4.28/4.5). My best soft skills are effective communication, work well as team and passionate for learning new skills. Noteworthly, I hold a PhD degree in R&D science and I worked for 5 years at the University of Toronto managing a laboratory and mentoring students. 
I love the fact your company is also in Portugal. I’m fluent in Portuguese and English and I am a permanent resident of Canada. 

For your convenience, please visit Features in my LinkedIn profile to see some React projects examples that I have developed:
https://www.linkedin.com/in/molinaro-raphael/

Please let me know when you are available for a discussion.

Thank you,
Raphael Molinaro
