### ISSUE TITLE
8Relocate - FullStack Engineer 

### ISSUE THREAD

**Issue by Yulia8Relocate** [TechnologyMasters/jobs#36]
### Salary Expectation

- negotiable
- Full Time

### Benefits

Pension Scheme;
Flexible hours;
German Classes;
Sport Groups;
Adventure days;
Learning & Development;
Visa Sponsorship;
Help with Relocate

### Location

- Munich, Germany
- Remote NO

## What You'll Do _(Job Description)_

We're looking for someone who will:

- Ship products that clients love to use!
- Take responsibility for planning, execution and success of complex projects.
- Team play together with other smart data and software engineers.
- Roll up your sleeves and code to get your project done.

### Must Have

- 4 years+ experience implementing beautiful and scalable web applications.
- Mastery of JavaScript;
- Expert HTML & CSS knowledge. (Don’t worry, we have designers that write HTML/CSS for you.)
- Working knowledge of relational databases.
- Good algorithms knowledge.

### Nice to Have

- Python

## About Our company

Our client is building extensive and easy to use web applications that have a huge impact on the travel industry. The team works with JavaScript, Python and Ruby (Big Data, Machine Learning and Natural Language).

## How to apply

Please send an email to [ay@8relocate.com](ay@8relocate.com) with your resume, use 'FullStack Developer' as subject

---

## Meta

- [x] Full Time
- [x] Remote NO
- [x] Relocate

**Comment by theetrain** [comment]
Hi @Yulia8Relocate, please include the company name in the title. If you cannot, I will have to close this and your three other posts.

**Comment by theetrain** [comment]
Closing until full company details are provided.
