### ISSUE TITLE
Node API 3+ Month Contract

### ISSUE THREAD

**Issue by Zdeaks** [TechnologyMasters/jobs#372]
Hey everyone, we're looking for an engineer to help us build out a node API for a dashboard that enables users to manage billing + team membership for a saas product. Work would be 40 hours / week and run 3+ months and you'd be joining to two other engineers we have working on this engagement. React and/or ops experience would be nice to have and we're looking for someone with at least 5 years experience. Ideally this person would be open to contract to hire though that's not a requirement. The engineering team is distributed across the U.S. and Europe. If this sounds like a fit please reach out with your linkedin/resume, location, and rates. Thanks!

**Comment by congnguyenthanh** [comment]
@Zdeaks 
Interest!

**Comment by ContentSpecialist** [comment]
Hey @Zdeaks 

Are you open to hiring remote experts? If so, I have a unique proposition that I think you'd be interested in.

**Comment by theetrain** [comment]
Closing due to missing information:

- Company name
- Location
