### ISSUE TITLE
It’s National Worship of Tools Day! celebrating that satisfying moment when you realise you have exactly the right tool for the job. 

### ISSUE THREAD

**Issue by theharrisonmoore** [TechnologyMasters/jobs#378]
WE’RE HIRING for a full-stack developer in London to help us build new tools for tradespeople – digital tools, that is.

:computer: :round_pushpin: :iphone: We’ve spotted a big opportunity to use tech to solve today's gig-work problems. Crowdsourcing could spread better job-related information. Ratings and reviews could help to improve working conditions. Online networking could turn isolation into belonging.

If you’re a purpose-driven coder and you want your work to have real results, then come join us at this pivotal moment. Start your application now. You don’t need a CV, just your brain. The deadline is coming up soon: Apply here: https://app.beapplied.com/apply/uw0andhgsy?utm_source=slack

**Comment by kspaans** [comment]
Please don't spam the same job post multiple times.
