### ISSUE TITLE
Tribaja- Junior Wordpress Engineer-  

### ISSUE THREAD

**Issue by NateV24** [TechnologyMasters/jobs#379]
### Salary Expectation

- $110,000/month
- Full Time

### Benefits

Team-oriented, collaborative environment encouraging continuous learning and ambition
Competitive salary, 401k, and health benefits (medical, vision, dental)
A Macbook will be provided to you for your business activities
Flexible work schedule
Basic membership to Indy Hall available, if desired
Catered Friday lunches

### Location

- Philadelphia, Pennsylvania

## What You'll Do _(Job Description)_

We are looking for a Junior WordPress Engineer to join our dynamic team! This person should be a strong, independent developer, able to discern customer requirements and convert them into technical specifications and ultimately product features. The successful candidate must have a track record and portfolio developing, deploying, and operationally supporting WordPress websites at scale. As a team member, the Junior WordPress Engineer will guide other engineers and share best practices in the WordPress ecosystem, website development, operational support, optimization, and analytics.

This is a full-time, salaried position with benefits. Post-pandemic the successful candidate will be expected to work out of our Philadelphia office with occasional client visits in the Greater Philadelphia Area.

### Must Have

3-5 years of work experience building and maintaining custom WordPress sites and themes
Working knowledge of the WordPress plugin ecosystem and custom plugin development
Experience with website performance optimization, SEO, digital marketing, and analytics integrations
Demonstrated fluency in building and embedding custom application logic into WordPress website with standard languages and frameworks:
e.g., Javascript, HTML/CSS, Angular, React
Excellent communication and collaboration skills
B.S. degree in Computer Science or comparable level of knowledge

## How to apply

If you are interested in exploring this opportunity, please send your updated resume and cover letter to nate@tribaja.co

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by hamza1886** [comment]
@NateV24 please clarify **$110,000/month salary** if it's correct? or is it per annum?

**Comment by NateV24** [comment]
> @NateV24 please clarify **$110,000/month salary**, is it correct? or is this salary per annum?

That is $110k per month
