### ISSUE TITLE
3-6 Month Contract Rails Developers

### ISSUE THREAD

**Issue by Zdeaks** [TechnologyMasters/jobs#381]
Hope everyone is doing well! We’re looking for several senior rails developers with 5+ years experience for a 3-6 month long contract. The company is growing rapidly and needs to bring on some extra help to manage performance issues and deliver new features. Current team is less than 10 engineers, and they could be open to a contract to hire. Remote preferred but candidates would need to have substantial (4 hours or more) overlap with EST working hours. If that sounds like a fit please reach out to me directly with your resume/linkedin, rates, and location. Sorry, no agencies. Thanks!

**Comment by theetrain** [comment]
Closing this due to missing information:

- Company name
- Location
