### ISSUE TITLE
Full Stack Engineer (typescript, javascript, react.js)

### ISSUE THREAD

**Issue by Joshmcgraham** [TechnologyMasters/jobs#393]
[EHAB] - [Full Stack Engineer] - [Remote]

**Intro**
EHAB is a fast moving startup, founded in the UK but now working 100% remotely. We combine distributed ledger technology, parametric insurance and advanced weather modelling to help the construction industry tackle rising weather and climate risk. We're on a mission to re-write the way risk is dealt with in the construction industry and help build climate resiliency.

As an employer we will give you the opportunity to work on cutting edge tech, invite you to contribute to product, company strategy and, most importantly, we want you to develop personally and professionally as the team and company does.

**Role**
We're looking for a Senior full-stack developer with solid experience in Typescript, Javascript, React, some Python experience, Hyperledger (or any other smart-contracts programming language for DLTs), Google Stack (Firebase, Firestore, Functions), DevOps (Docker, servers configuration).

More importantly, we're looking for someone who's comfortable navigating between multiple technologies, and open to working with whichever tool/framework/language is best suited to a given problem.

Must also be comfortable with having a high level of autonomy and rapid problem solving.

**Requirements**

- Availability to start in June/July.
- Fluent in Typescript and Javascript.
- Solid knowledge of React.
- Hyperledger (or any other smart-contracts programming language for DLTs).
- Experience with Google Apps stack (Firebase, Firestore, Functions).
- Solid knowledge of DevOps (Docker, server configuration, etc.)
- Concerned with user experience, not just with code quality.
- Takes initiative.
- Professional, versatile and comfortable with agile methodologies.
- The company
- Work as part of an incredibly flexible and agile, multi-disciplinary team.
- Career development opportunity as the company and team scales.
- Flexi-working and remote working, offered and encouraged.
- Chance to have more responsibility and contribute to the future of the company.

**The technology**
Developing solutions to problems that have yet to be tackled, in other words: it’s cutting edge!
Working on technology which is defining the national and international standards for smart contracts in construction.
Numerous opportunities to work with and learn new skills and technologies.

**Values**
Great! You’ve read this far and you’re still reading. Now comes the final crux.

As a company we want to empower people to live their best life, to be curious and to flourish. We don’t want to work you to the bone, but we also expect high performance to be the norm. We want to be as flexible as we can to enable your way of life, as the happier you are the the happier we are.

Ultimately we want to create an environment which is equal parts; fun, challenging, and supportive. We want to make a difference and cause a positive impact in the world, and we know we can't do that alone. We need a community of motivated and curious people to help us all get there.

DM Josh Graham @TechMasters
[View role on AngelList](https://angel.co/company/ehabplatform/jobs/1211093-senior-full-stack-software-engineer)

**Comment by theetrain** [comment]
Please follow the title format from the job template

```
# Issue title format: [Company Name] - [Job Title] - [Location]
```
