### ISSUE TITLE
F3 Software - App Dev Team Seeking App Designer To Partner With - US / Remote

### ISSUE THREAD

**Issue by jeffhigham-f3** [TechnologyMasters/jobs#41]
### Salary Expectation

- Hourly rate or project rate (negotiable).
- Contract.

### Benefits

- Work from anywhere.

### Location

- US (preferred)
- Remote ok.

## What You'll Do _(Job Description)_

 I work with a small mobile development team and we are looking for a mobile designer to partner with on future projects.  I would prefer in the US but it is not a requirement. 

## What You Need to Be Successful _(Skills)_

- A firm understanding of IOS and Android UI/UX.
- Mobile development portfolio with apps published in the app store.

### Must Have

- 3+ years working as a mobile designer

### Relevant Experiences

- mobile technology
- User Interface design

## About Our company

Please visit: www.f3software.com

## How to apply

Please reach out to me via email: jeff@f3software.com. and we can continue the conversation.

---

## Meta

- [ ] Full Time
- [x] Part Time
- [x] Contract
- [x] Remote OK
- [ ] Fully Remote
- [x] Hourly
- [ ] Salary

**Comment by theetrain** [comment]
Please add more salary details such as a range.
