### ISSUE TITLE
QuickTapSurvey - Java Developer - Toronto, Ontario, Canada

### ISSUE THREAD

**Issue by warrent-github** [TechnologyMasters/jobs#42]
### Salary Expectation

- Based on skills and experience
- Full Time

### Benefits

- Catered breakfast every Friday
- Health/Vision/Dental benefits
- Unlimited snacks
- Hack day competitions
- Beer-o-clock Fridays
- Education & Training
- Gym membership
- Slack

### Location

- Toronto, Ontario

## What You'll Do _(Job Description)_

We are looking for a Java developer to join our engineering team. You will be working with our engineers to develop and maintain high quality web applications. We’re working on exciting new features with the latest technologies.

## What You Need to Be Successful _(Skills)_

- At least 5 years of Java Web Application Development Experience
- Java, Spring (MVC), J2EE (JSP, servlets, etc)
- Web and Java design patterns
- Eclipse/IntelliJ IDE
- Git with Gitflow
- MySQL Database Server or RDBMS equivalent (Oracle, Postgres, etc)
- SQL language
- Front-End Experience: HTML / CSS / JavaScript, JQuery
- Unit Testing (JUnit or TestNG)

## Bonus Points if you have experience with...
- Apache Tomcat Server v8
- Hibernate
- Scalable web architecture design
- React/Angular
- Gradle/Maven
- Amazon Web Services (EC2, SES, S3, CloudWatch, etc)

## Education Requirements
- University Degree - Bachelors of Computer Science, Computer Engineering, Software Engineering or equivalent

## About Our company

Our vision is to be the world's leading in-person survey platform. We're always looking for smart, passionate and motivated people to join our quickly growing team in Toronto, Canada. Being a small company, you'll be given the opportunity to grow your career quickly and take on as much as you can handle!

## How to apply

https://www.quicktapsurvey.com/careers
- Please indicate your referral from myself, Warren Tom, Quality Assurance Manager
- We are not currently accepting applications from agencies.

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by theetrain** [comment]
Please add more salary details such as a range.
