### ISSUE TITLE
Dig Insights - Intermediate Front-End Developer - Toronto, Ontario

### ISSUE THREAD

**Issue by ldoi** [TechnologyMasters/jobs#43]
## Preface

Dig Insights Inc. is an innovative market research company located in downtown Toronto. At seven-years-old, we’re continuing to grow quickly. We’re looking for a Front-End  Developer that can help us build our custom interfaces, web applications, dashboards, mobile applications, and other innovative online tools. This position plays a key role in developing, updating, and building out our exciting tools and services. We work fast and learn fast.

Being part of a small company is different than being part of a large company. It is not for everyone, but for the right candidate, this is a great opportunity. Our dream candidate is someone who is able to work independently, problem-solve and think outside the box. Beyond that, we need creativity, intelligence, a great work ethic, self-motivation, and a sense of humour.

### Location

- Toronto, Ontario

## What You'll Do

·      Work with Dig colleagues to help develop our complex survey interfaces and web applications

·      Help start and update projects in new JS frameworks

·      Offer insights and be self-sufficient whike working to make complex front-end development decisions

·      Work effectively with other members of our web team throughout the build cycle

### Must Have

·      College/University Degree/Diploma in web/software/media development (or equivalent)

·      2+ years experience (or equivalent proficiency) in the following: HTML5, CSS 3.0, Javascript, Ajax

·      Experience with Adobe Suite and wire-framing tools

·      Experience with Responsive adaptive web design

·      Comfortable updating legacy jQuery, PHP code

·      Knowledge of  Javascript frameworks such as React, Angular, Polymer

·      Experience with version control, git flow model

·      Solid coding fundamentals, proper styling, commenting, and comfortable with conducting peer code review

·      Willing and able to work within a fast-paced dynamic environment

·      Ability to work within and meet tight deadlines

·      Demonstrated work ethic, integrity and professional conduct

·      Ability to work independently and with a team

### Nice to Have

·      Experience with designing forms and testing frameworks

·      Experience writing client/server applications over RESTful web services

·      Experience with mobile UI frameworks (eg. React-Native)

·      Experience with UI frameworks (eg. React, Angular)

·      Experience setting up frameworks and installing libraries

·      Experience working with databases
  
### Relevant Experiences

·      Comfortable working with AWS and cloud deployment

·      Familliarity with ES6

·      Experience or Familliarity with git flow model

## How to apply

Please send an email to long@diginsights.com and cc: careers@diginsights.com

![image](https://user-images.githubusercontent.com/33432404/33092446-2a0c60e8-cec8-11e7-9e94-c8c5656c3eac.png)

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by theetrain** [comment]
Please add more salary details such as a range.
