### ISSUE TITLE
Mass Hiring event at Civis Analytics

### ISSUE THREAD

**Issue by asolkoff-civis** [TechnologyMasters/jobs#431]
Hey everyone! Civis Analytics is having a mass hiring event for the next couple of weeks and I wanted to share that we are looking for a whole bunch of Data Scientists, DevOps Engineers, and Software Engineers! If you’re interested, please use the following link to apply!

To be eligible you must:

1. Reside within the United States currently
2. Not require sponsorship to work in the United States now or in the future

These positions can remain remote.

If you’re interested please click on the link below and apply to any of the “all levels” roles in the Technology section.

[](https://www.civisanalytics.com/careers/)

**Comment by amanda-3329** [comment]
Hello- where is the link?
