### ISSUE TITLE
MakeLab - Junior Technologist + Field Manager - Toronto

### ISSUE THREAD

**Issue by JonathanOfMakeLab** [TechnologyMasters/jobs#46]
### Salary Expectation

Paid + Full-Time (6 Month Position)  |  Entry Level  |  Starting Early/Mid January

### Benefits

- Opportunity for paid travel-work adventures
- Fast-paced learning environment between advertising, marketing and event planning fields
- Opportunity for contract extension
- Free access to 3D printers and laser cutters for personal projects
- Front row view of a high-growth startup
- Health benefits after three months of employment

### Location

- Toronto, Ontario

## What You'll Do

We’re looking for a energetic, gets-shit-done graphic designer and technologist to join our close-knit creative team. Our studio is a secret weapon for event planners, agencies, and brands in Toronto and around the world. Our tech projects almost always involve an interactive experience at a live event, which makes our studio fast-paced. We each wear many different hats, in building our thriving creative studio. Your experience will be no different – splitting your time between in-studio production and on-site event execution. In studio, you will assist with with a variety of technical design tasks to prep. On-site at events, you'll be leading members of our events team and coordinating with clients to bring the plan to life. Your work will be challenging and your opinions will matter. An independent, forward thinking mindset will serve you well, as will a willingness to do, fail, learn, and repeat. This is a full-time entry level position with irregular hours, which means you'll need the flexibility to work evenings and weekends on relatively short notice.

**Design**
You’ll assist with graphic design and layout projects for print, projection, and laser cutting.

**Technical**
In studio, you’ll manage our tech inventory, build tech processes, and pack for events. At events, you’ll help set up our technical interactives and troubleshoot in a live, client-facing environment. You’ll also be on-call when our events team needs tech support at events.

**Production**
You’ll assist with our laser cutting and 3D printing prototyping work.

**Field Management**
Often you’ll lead our teams on-site in executing our technical events.

**Operations**
You'll help with a wide variety of operational errands, from supply pickups to equipment maintenance.

## What You Need to Be Successful

- You have worked on New Media projects, and you have a high degree of experience with technology, from computers, to networking and AV setups.
- Your friends describe you as energetic and outgoing, with a get-shit-done attitude
- You can handle a flexible schedule and are able to work evenings and weekends
- You're an exceptional communicator
- You’re a collaborator and can take charge when necessary
- You feel comfortable lifting heavy equipment more than 100 lbs. (This is really important, as you will be regularly helping move heavy equipment)
- You must have a driver's license and are comfortable driving long distances
- You have your passport, can travel to the USA and overseas, and like to do so
- You don’t mind the small tasks and know they make all the difference in the big picture

### Nice to Have

- Experience in the field of marketing, communication, or event planning
- 3D design experience for 3D printing
- Experience with using 3D Printers, laser cutters, or other Maker tools

### Relevant Experiences

- mobile technology
- User Interface design

## About Our company

Three years ago, we took eight 3D printers to a Toronto bar and taught design ‘till last call. We’ve since taken all our tools out of the lab, inventing ways to spark wonder and creativity in unexpected places. We stretch technology beyond its design intent, creating accessible, collaborative, and interactive experiences at events around the world. Our studio is filled with laser cutters, light tables, fabric printers, projectors and food photo booths. Creative people looking to solve interesting technical and design challenges will find their place here.

## How to apply

Learn about our studio at [www.makelab.ca](http://www.makelab.ca), then please apply via [Workable](https://makelab.workable.com/). We regret that we are unable to reply to applications sent via email. While we read every resume and portfolio piece, only candidates under consideration will be contacted. MakeLab is an equal opportunity employer and is committed to inclusive hiring practices. 

---

## Meta

- [x] Full Time
- [ ] Part Time
- [x] Contract
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by theetrain** [comment]
Please add more salary details such as a range.
