### ISSUE TITLE
React + Redux Engineer (Contract)

### ISSUE THREAD

**Issue by ma2780** [TechnologyMasters/jobs#461]
Forward - React + Redux Engineer - Remote

- Contract / Full Time
- Remote

Hey everyone! Looking for a react + redux engineer to help out a 3-person team for 40 hours/wk. The role is remote and the contract would last 3-6 months. You can read a bit more about the role here: https://flossy-cat-f0a.notion.site/React-Redux-Engineer-Contract-5d0eed60d6264d4882798bccc14d21a7

Ideally you:

- have 3+ years experience with react + redux
- have 40 hours a week of availability for 3-6 months
- have 4+ hours of overlap with ET
- have startup experience

If you’re interested, please feel free to DM me with your resume. Thanks!

- [ ] Full Time
- [ ] Part Time
- [x] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [x] Remote Regional
- [ ] Remote OK

**Comment by billogawa** [comment]
Hello
I am a react/redux developer with 7 years experience

**Comment by billogawa** [comment]
I am looking for new opportunity
