### ISSUE TITLE
Nudge Rewards - Senior Full Stack Developer - Toronto

### ISSUE THREAD

**Issue by nahmednudge** [TechnologyMasters/jobs#47]
### Salary Expectation

- Competitive Salary
- Full Time

### Benefits

- Professional development allowance 
- Monthly hack days
- In office Yoga twice a week
- Flexible health and wellness benefits
- Stocked fridge and healthy snacks
- Bike parking
- Dog friendly office

### Location

- Downtown Toronto, Ontario

## What You'll Do 

We're looking for a [senior engineer](https://www.nudgerewards.com/senior-full-stack-developer) to join us in building and enhancing our employee engagement product. Our current code base includes technologies like Rails, React, MySQL, Redis, and Sidekiq. Aside from proven technologies, we're looking into and experimenting with Elixir, Vue.js, Elm, and Tensorflow, just to name a few. You will be adding new technologies into this mix.

As a senior engineer, you've encountered and solved problems across the full server-side stack. You are enthusiastic about designing, implementing, and testing new features. And you're comfortable delving down into server-side configurations, and bubbling up into the DOM to manage event handlers.

## What You Need to Be Successful

- 5+ years of experience building and scaling web applications
- Previous history as a senior developer (or you're ready to make the jump)
- Familiarity with industry-wide patterns and practices
- Willingness to collaborate across multiple teams
- Comfort with a variety of testing strategies
- Strong verbal and written communication skills

### Must Have

- Architecting, building, deploying and maintaining features
- Full Stack analytics

### Nice to Have

- Future integrations with Point of Sales systems and other enterprise-level software
- Future integrations with machine learning and AI
- Designing the long term vision of the app

## About Our company

[Nudge Rewards](https://www.nudgerewards.com/) is reinventing team performance for the non-desk workforce. We deliver a mobile solution designed to engage, educate and reward front-line managers and employees to improve team performance and increase profitability. Leveraging the combined power of a mobile app, behavioural theory, and powerful analytics, Nudge helps companies guide, measure, and ultimately reward their teams for exceptional performance. Nudge is the radar system that allows organizations to anticipate and improve the performance of their teams in real-time.

There are 500M+ frontline employees around the world, who often miss out on important news, promotions, sales and operational content because companies fail to engage with them through traditional means.

Nudge addresses this problem head-on by providing a powerful platform that harnesses the power of employee’s smartphones, habits and a powerful analytics back-end to streamline communication and engagement.

## How to apply

Interested in this role? Please send your resume, LinkedIn and Github profiles to engineering@nudgerewards.com

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by theetrain** [comment]
Please add more salary details such as a range.
