### ISSUE TITLE
Filament Creative - ETL & Data Viz contract - Toronto/Remote

### ISSUE THREAD

**Issue by varco** [TechnologyMasters/jobs#49]
### Salary Expectation

- Negotiable
- Contract (60 days)

### Benefits

- Opportunity to work from Carpet Factory Lofts in Liberty Village
- Work from home or remotely if desired

### Location

- Toronto, Ontario
- Remote OK

## What You'll Do _(Job Description)_

Looking for a freelancer or consultant for ETL (extract transform load) and data visualization (D3.js) for a contract with deliverables at end of March. 

## What You Need to Be Successful _(Skills)_

- Experience integrating ETL software into web interface
- Experience with Data Visualization framework (D3 is preferred)
- Experience working with Angular 

### Must Have

- Be able to make recommendations and explain the reasoning for decisions made.

### Nice to Have

- Writing Angular unit and end to end testing.

## About Our company

Filament Creative is a digital agency delivering custom experiences for clients.

## How to apply

Please send an email to [les@filamentlab.com](les@filamentlab.com) with a link to relevant examples and your online profile, use 'ETL & Data Viz Developer' as subject

---

## Meta

- [ ] Full Time
- [ ] Part Time
- [x] Contract
- [x] Remote OK
- [ ] Fully Remote
- [x] Hourly
- [ ] Salary

**Comment by theetrain** [comment]
Please add more salary details such as a range.
