### ISSUE TITLE
Backend Developer 

### ISSUE THREAD

**Issue by maiteio** [TechnologyMasters/jobs#502]
**Backend Developer - US ONLY - 100% Remote - CY9

Compensation: $112,000 to $140,000 Annually**

Our client is looking for a backend focused, mission driven Senior Developer to join their Research and Development team.

**Position Responsibilities**

- Leads cross-functional development to bring prototypes to life, providing constructive feedback to optimize implementation and usability
- Embrace emerging standards while promoting best practices while communicating tradeoffs
- Collaborate with product, services, sales, etc. to determine priorities and risks associated with projects
- Ensure all relevant processes, procedures and product documentation is up to date
- Follow continuous integration/continuous development processes, peer review, coding style, and development conventions using version control systems (bitbucket/git)
- Actively participate in team standups, the LeSS agile process, peer code reviews, and occasional pair programming
- Collaborate with other developers on planning and working use cases, features, and tasks
- Required Experience, Skills and Knowledge
- 3+ years of deep JavaScript experience with experience across the development stack
- Experience interacting with Restful APIs, GraphQL APIs and AWS services
- Demonstrated understanding of data storage, caching, and modeling practices
- Demonstrated understanding of design paradigms, software architecture, and design patterns
- Willing to solve engineering challenges new to them and the team
- Ability to travel occasionally
- Ability and interest to work remotely from a home office when not at a corporate office
- Ability to pass a pre-employment background and drug screen in accordance with applicable laws

**Preferred Experience, Skills and Knowledge**

- Experience with TypeScript
- Experience with AWS CDK
- Experience with AWS Fargate, EKS, or similar
- Experience with PaaS/SaaS patterns utilizing a serverless approach
- Comfortable working in a dynamic environment driven by external demands
- Community-oriented/involvement in thought leadership demonstrates trade expertise
- Familiar with LeSS Methodology, or system decomposition and work task organization, as used in Agile methodology

Please connect with me on Linkedin if interested in the role, or e-mail me your resume at maite@cy9.io

https://www.linkedin.com/in/maite-robles-/

**Comment by future-mine** [comment]
I am interested in the job.

**Comment by maiteio** [comment]
Please reply with your resume, and note: This is a US based job only.

Thanks!
