### ISSUE TITLE
Statflo - Engineering / General - Toronto

### ISSUE THREAD

**Issue by stevepereira** [TechnologyMasters/jobs#51]
### Salary Expectation
- Competitive salary (80-130k)
- Full Time

### Benefits
- Relocation assistance
- Visa sponsorship
- Downtown office (benefit for most?)
- Open leadership
- Lots of advancement opportunity
- Weekly all-hands collaboration
- Dedicated hack/experimentation time
- Flexible hours
- Free snacks/breakfast/lunches
- Regular team celebrations
- Quiet areas / Open office
- Dedicated downtime/games space
- Transit/Parking subsidy
- Gym subsidy
- Team yoga
- Sport groups
- Adventure days
- In-office massages
- Constant learning & development

### Location
Toronto, Ontario

## What You'll Do _(Job Description)_
[Statflo](https://statflo.com) needs smart people who work well with others to build amazing things that make people happy. This is a generic post to reach awesome people of all areas of focus and experience around engineering. We need help scaling our engineering capacity to make greater products, better and faster all the time. You will: 
- Create MVP tools and products that won’t scale
- Test them to make sure they do what they need to
- Reinforce them to withstand the tests and trials of time
- Automate everything to run like clockwork
- Share knowledge about what you’ve learned
- Work with team mates in all types of roles
- Consider the customer’s, company’s, team’s and future goals when making decisions
- Level up everyone around you
- Absorb the collective brilliance of your tribe and team
- Do and learn new, awesome things all the time

### Must Have
- Formal education in a technical field or clearly demonstrated technical experience
- 2+ years of relevant employment experience with proven results
- Very strong engineering ability ideally in Python, Java or Scala but we are open to other experience if you would like to become a Java/Python hacker
- Results-oriented, data-driven, experimental attitude towards your work
- Attention to de_tail
### Soft Skills:
- Proven experience making reasoned, clear decisions and compromises while delivering work at high velocity
- Boundless positivity and drive to improve
- Strong sense of both ownership and humour
- Effective communication and strong collaboration skills
- Strong troubleshooting and problem solving skills

### Nice to Have
- Data engineering
- Team leadership
- Process automation

### Relevant Experience
- Data driven SaaS engineering
- Microservice architecture
- AWS

### Other positions
We're also interested in:
- Product (Data focus)
- QA/Automation engineering
- Full stack development

## About Our Company
Raise your hand if you have a phone. Keep it up if you love dealing with account changes, bills, accessories, upgrades, call centres and retail store staff.
[Statflo](https://statflo.com) works with telecom carriers and technology retailers across North America to keep those hands up.
### What we do:
- Engage retail staff by gamifying their day to day experience - making it easy for them to hit their goals and stay more engaged at work
- Enable stores to stay in touch with local prospects and past customers using messaging or phone
- Train and motivate retail teams to improve their culture and hold people accountable to provide amazing customer service, every time
### Why it matters:
- Millions of retail workers are handed a broom or become Facebook-scrolling zombies during the 8 hours they are idle each week. We challenge this norm by empowering them to increase sales themselves
- Millions of customers of wireless carriers and technology retailers want a better customer experience that is personal, proactive and consistent

## How to apply
Please send an email to [engineering@statflo.com](engineering+techmasters@statflo.com) with your resume, and use 'Engineering' as the subject
---

## Meta
- [X] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [X] Salary

**Comment by theetrain** [comment]
Please add more salary details such as a range.

**Comment by stevepereira** [comment]
@theetrain done :)
