### ISSUE TITLE
Sago Mini - Full Stack Web Developer - Toronto 

### ISSUE THREAD

**Issue by colinmccune** [TechnologyMasters/jobs#52]
### Salary Expectation

- Competitive Salary
- Full Time

### Benefits

- Free weekly team lunch
- New Macbook
- Regular board game, D&D, and movie nights
- Stocked fridge and snacks

### Location

- Downtown Toronto, Ontario

## About The Job

[Sago Mini](https://sagomini.com/en/our-story/) is hiring a full stack web developer. You’ll join a team of designers, developers, builders, artists, thinkers, and doers. We make fun apps and toys to delight both kids and parents around the world. This is an intermediate/senior role that requires a candidate who has strong technical chops and enjoys working independently. You’ll be responsible for leading the development of our internal web apps and the web services used by our mobile apps.

### Requirements
- 5+ years building, deploying and maintaining web applications and services.
- Experience with modern backend and frontend web development stacks (eg: Node.js, Express.js, AngularJS, HTML5, CSS/SASS, and jQuery).
- Acted as a lead developer on multiple projects.
- Able to break down complicated tasks into distinct solvable pieces, prioritize what is important, iterate quickly, and write clear and reusable code.
- Prior experience building RESTful APIs and web services.
- Familiar with designing for non-relational (MongoDB) and relational (MySQL) databases.
- Comfortable working day-to-day with remote team members and juggling multiple projects.
- The terminal is your best friend and you enjoy wearing the DevOps hat (AWS, networking, Ubuntu Linux, security, and using automation tools like Ansible).

### Also Import
- A degree in computer science/computer engineering/web development or a resume full of practical experience.
- Eager to learn new things, solve hard problems, and hustle.
- An eye for visual design and the ability to work collaboratively with designers and artists.
- Able to communicate technical concepts to non-tech team members.
- Open to exploring C# and the Unity game engine.
- Willing to occasionally travel to Stockholm, Sweden and San Francisco, California.

## About Our company

Sago Mini is an award-winning company devoted to play. With over 26 million downloads, 25 apps and a new line of physical toys, Sago Mini brings thoughtful design to life for preschoolers and parents worldwide. Based in Toronto, Sago Mini is a subsidiary of Toca Boca, the No. 1 mobile-first kids brand in the App Store. We offer an exceptional workplace in downtown Toronto and competitive compensation. We hire humble, collaborative, and ambitious people who care about about doing great work. Sago Mini is an equal opportunity employer. We value diversity at our company.

## How to apply

If this sounds like a job for you, then don’t be shy and reach out and say ‘Hello’, https://goo.gl/7BfLjc. Tell us about work that you're proud of, your hobbies, and what excites you about working at Sago Mini.

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by theetrain** [comment]
Please add more salary details such as a range.
