### ISSUE TITLE
Honeypot.io - Software Developer - Berlin, Amsterdam, Hamburg, Munich, or Stuttgart

### ISSUE THREAD

**Issue by hunterwright696** [TechnologyMasters/jobs#54]
### Salary Expectation

40K-120k

### Benefits

- Get multiple job offers
- Only one profile, no applications
- Choose which tech-stack you want to work with

### Location

- Berlin
- Hamburg
- Amsterdam
- Munich
- Stuttgart

## What You'll Do _(Job Description)_

Looking for Software developers with at least 2 years of experience who are willing to work in Germany or the Netherlands. 

### Must Have

- 2+ years experience as a Software Developer

## About Our company

We help with VISA sponsorship 

## How to apply

Follow this link: https://goo.gl/9Me2jw

---

## Meta

- [x] Full Time
- [x] Salary

**Comment by theetrain** [comment]
Please include more details:

- salary figure or range
- check the 'meta' checkboxes to apply labels
- change issue title to the proper format: Company - Title - Location

**Comment by hunterwright696** [comment]
Hi @theetrain thank you for your help. I changed it and added the salary range, changed the title, and also checked the right meta checkboxes. 

Cheers!

**Comment by ahmadnassri** [comment]
missing apply link

**Comment by hunterwright696** [comment]
@ahmadnassri done! Thank you
