### ISSUE TITLE
 Firstly - NodeJS Developer with Devops experience - Remote Americas, Europe

### ISSUE THREAD

**Issue by joelkaufman** [TechnologyMasters/jobs#545]
# Firstly - NodeJS Developer with Devops experience - Remote Americas, Europe

### Salary Expectation

- $50-$60/Hour
- Contract / Full Time

### Benefits

- professional team (we dont hire mediocre people)
- potential full-time

### Location

- Remote
- Americas - Europe

## What You'll Do 

We're looking for someone to assist with a NodeJS scraper

## What You Need to Be Successful 

- NodeJs
- serverless.com
- AWS lambda
- AWS ECS (docker)
- Kubernetes

### Must Have

- Expert NodeJS developer
- Familiar with devops  

## About Our company

We are a Salesforce Consultancy Located in Mahwah NJ Looking to expand our team, this is a remote position and does not require travel.

you will be working with a group of remote developers with a strong, agile development culture; we use the latest tools and tech and focus on building stuff, not writing extensive specs, and sitting through long boring meetings..

## How to apply

https://forms.gle/hs1pSzzhwqZ1gAwW8

## Meta
- [ ] Full Time
- [x] Part Time
- [x] Contract
- [ ] Internship
- [x] Remote Worldwide
- [ ] Remote Regional
- [x] Remote OK

**Comment by consumer-tasks** [comment]
Location: LOS ANGELES CA
Technologies: JavaScript, React, NextJS, GatsBy, AWS, Node, Express, MySQL, TypeScript, Srapi, Algorand, Blockchain
Resume/CV: https://drive.google.com/file/d/1g6FKmjBLqccOk6710LNjDYEbVuC3d6gu/view?usp=sharing
Website: https://www.linkedin.com/in/codepro/
Email: farlight216@gmail.com
