### ISSUE TITLE
Perry & Currier - .net developer (Contract role) - Toronto, Ontario

### ISSUE THREAD

**Issue by bzaba** [TechnologyMasters/jobs#55]
Salary:  negotiable (Contract)
hourly or completion of project

### Location

- Toronto, Ontario
- Remote OK after project details 

## What You'll Do _(Job Description)_

We need a .net developer to develop an application that will involve establishing a TCP tunnel to update a SQL server db.

### Must Have

- experience writing desktop apps for a windows environment
- SQL Server experience

### Nice to Have

- C#

### Relevant Experiences

- desktop app experience

## About Our company

http://www.pckip.com/

## How to apply

Please send an email to bohdan@fortay.co with your resume, use '.net contract' as subject

---

## Meta

- [ ] Full Time
- [x] Part Time
- [x] Contract
- [ ] Internship
- [x] Remote OK
- [ ] Fully Remote
- [x] Hourly
- [ ] Salary

**Comment by theetrain** [comment]
Please add more salary details such a range.

**Comment by bzaba** [comment]
Contractor has been selected.  Thank you everyone for your interest!
