### ISSUE TITLE
Hire Developer C++ for Wavelens AR-Project

### ISSUE THREAD

**Issue by DerDennisOP** [TechnologyMasters/jobs#576]
Hello, Hope you're all doing great!

I recently started a Project called "Dimension". I'ts about Metaverse and Virtual Reality.
Likewise, I'm looking for programmers and devs in HW and SW. There is no payment, so if you
are interested to code together with 10 other people on a really great project,
please do not hesitate to DM me and ask for more details.

We're looking for all kind of Developers and Engineers. The main part is coded in C++.

Best wished,
Dennis

**Comment by kspaans** [comment]
Closing this as it isn’t a job ad. Please use the #showcase channel in Slack if you want to promote your project.
