### ISSUE TITLE
Contra - iOS Mobile Engineer - Remote

### ISSUE THREAD

**Issue by yccgabby** [TechnologyMasters/jobs#591]
### Salary Expectation

- $75 USD/month 
- Contract 

### Location

- Remote
- U.S. based preferred

## What You'll Do _(Job Description)_

We are Vive Concierge, Inc, virtual healthcare, lab services, and wellness company based in Los Angeles, CA. We focus on achieving health equity and wellness through the deployment of digital solutions for urgent, primary, and preventative care. Our work exists at the intersection of technology and policy focused on advancing the achievement of better outcomes for patients across all economic spectrums, domestically and internationally. Vive is democratizing concierge medicine!

We are looking for a remote Mobile Engineer who is U.S. based and focused on iOS to join our engineering team at Vive! In this role, you’ll balance individual contributions. You’ll work on some of our most exciting and complex projects. Mobile Engineers focus on building out our mobile technology infrastructure and are responsible for helping to grow Vive’s reach and drive increased patient conversions. You’ll build scalable products that make the healthcare experience for patients, and providers safer, and more efficient.

### Must Have

- Passion for technology and the ability to think critically about performance, scalability, and reliability of software
- 3+ years of iOS development experience
- Knowledge and experience with backend API services (REST API and GQL)

### Nice to Have

- A Computer Science or related degree is preferred, but not required
- Swift expertise is preferred

## About Our company

Contra is a new professional community for your independent journey as a freelancer. Check out our [State of Independence](https://contra.com/freelance-industry-report-2021/) to learn more about the freelancer industry and how Contra empowers the independent economy!

## How to apply

Please apply directly on Contra through this [link](https://contra.com/opportunity/BBvxTmdS-i-os-mobile-engineer-in-healthcare)

---

## Meta

- [x] Full Time
- [ ] Part Time
- [x] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [ ] Remote Regional
- [x] Remote OK

**Comment by VoV40k** [comment]
Hey Gabby, I could suggest a candidate for the role. Let me know if you could talk in zoom or so, please. My email is vladimir.smirnov@litslink.com
Cheers!
