### ISSUE TITLE
DevProx - Senior PHP Developer - Remote

### ISSUE THREAD

**Issue by proriri** [TechnologyMasters/jobs#598]
Hi all.

We at DevProx are looking for a skilled **Senior PHP Developer** with at least 5 years of experience to work on an ongoing project. We need someone that is looking for a long-term/stable engagement with the freedom to dictate their own hours. (Time commitment: Contract).

### Description
_ _ _

+ Step into an ongoing project
+ Need to ensure a seamless interchange of data between the server and our users
+ Responsible for developing and coding all server-side logic, and periodically interfaces
+ You will be required to maintain the central database and work with other developers on the team
+ Architecting/Designing
+ Peer reviews
+ Programming
+ Ad-Hoc tasks as needed for this role

### Requirements
_ _ _

+ Minimum of 20 hrs/week required
+ Minimum 5 years of experience
+ PHP and MySQL
+ React and E-commerce experience would be a plus

### Offer
_ _ _

We prefer an independent contractor agreement and offer USD20-35 per hour.

If interested, please contact me at riaan@devprox.com.

**Comment by smart0815** [comment]
Hello, nice to meet you
How're you?
I have several years of development experience and I’m highly skilled in security, server maintenance, and new feature implementation
I developed multiple websites and web & mobile apps in the business, enterprise, and eCommerce fields
I'm familiar with python and their framework such as laravel, CI and wordpress.
I want to apply for the role as soon as possible
I will be available at your time

Thanks
Have a great day
