### ISSUE TITLE
Commit - Senior Fullstack Developer - Remote/North America

### ISSUE THREAD

**Issue by ejmudi** [TechnologyMasters/jobs#609]
# Commit - Senior Fullstack Developer - Remote (North America)

### Salary Expectation

- $115k - 140k (CAD)
- Full Time

### No more technical interviews

- Work with **over 70 pre-vetted impactful startups** in North America
- Gain access to **transparent salary bands AND mentorship** to grow your career 
- **Collaborate** with like-minded tech junkies 
- **Build new tools** with JavaScript, React, Node and much more!

Commit is a VC-backed remote-first community and accelerator program for Canadian senior software engineers looking to join some of Silicon Valley’s most innovative startups as one of the first engineers.

We work exclusively with startups who are financially stable, have great salaries, use an exciting tech stack, champion diversity and inclusion and care about supporting your growth. We provide all the info you need so you can make the right decision and continue to cultivate your craft.

### So how does this work?
- Apply to our Engineering Partner program
- Go through a brief 3-step interview process with Commit.
- If you’re accepted into the program, you will be **paid a full salary** while we work together to match you to a startup.
- Once matched, you work with a startup for 3 months. If you’re happy, you can stay with them; if not, we’ll work together to find a better match.

### Our Preferred Tech Stack
- FE: One/some of: Vue.js, React, Redux
- BE: One/some of: Golang, Node.js, Ruby/Rails, Python/Django (MVC!)

### What we offer during the program
- Full time paid employment as an Engineering Partner
- Base salary of $115K to $140K CAD depending on experience
- Extended health and dental plan for you and for your family
- The right equipment to do your best work
- Access to your own career coach and a mentor for your job search
- We provide 15 vacation days on top of statutory holidays while you're part of the Engineering Partner program. There is no limit on Sick Days or Personal Days
- Invitation-only events with technical leaders. We’ve been lucky to have guests like Katie Wilde (VP Engineering @ Buffer), Armon Dadgar (CTO @ Hashicorp), Gokul Rajaram (board member at DoorDash, Coinbase, Pinterest and The Trade Desk) and many others join us for private learning sessions.

### Location
- Remote North America

## About Our company

Commit is the first professional network founded by software developers that puts the career needs of Startup Engineers first. It’s a collaborative, remote community with life-long peer-to-peer support, personalized career development, and seamless career transitions with unique access to startup opportunities.

## How to apply
[https://jsjobbs.com/javascript-jobs/4h8ZIZtimmoC-senior-full-stack-developer-commit](https://jsjobbs.com/javascript-jobs/4h8ZIZtimmoC-senior-full-stack-developer-commit?ref=TM)
---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [x] Remote Regional
- [ ] Remote OK

**Comment by seitosolano** [comment]
Hi
Thanks for your invitation.
I reviewed your jobs carefully, and I decided to answer you.
I am sure that my experience and skills will be helpful for you to save your time and labour.

I would like to discuss more on an online meeting or phone.
If you are interested in my resume, Please let me know how to start my work with you.
And then I will make an appointment to take an interview with you.

I shared my resume in this email.

Thanks and Regards.

Seito Solano
Freelancer

555 Castro Street Mountain View, Santa Clara CA

Email: seitosolano1982@gmail.com
Phone: (650) 318-5218
SkypeID: live:.cid.bfbf2f881a5e64a7
[888_seitosolano_resume.pdf](https://github.com/TechnologyMasters/jobs/files/8691860/888_seitosolano_resume.pdf)

**Comment by smart0815** [comment]
Hello, thanks for your job posting
I already apply for the role via the link and I don't know if you can see, it or not
I'd like to discuss your project in more detail
I'm ready to share my experience via interview

I hope you're doing well
Best regards

**Comment by seitosolano** [comment]
Hi, Ejmudi.
Sorry for bothering you.
Something for your work figured out of mind, so that I dropped my notes again.

I would like to inquire a few of question.
•	is it on-going project or startup project?
•	do you have wireframe, layout design or meta, API requirement, database structure
preparation for integrating the 3rd party service like google, firebase or AWS
practical issue measurement such as estimation of payload on your service, such as responding time, concurrent access 
•	do you have a roadmap of your project

I would like to discuss more one by one about your project with your teams
I get used to take a discussion on online meeting like zoom or google.
Seito Solano
Regards.
