### ISSUE TITLE
Tech Lead - Immigration Refugees and Citizenship Canada

### ISSUE THREAD

**Issue by ShafiqShamji** [TechnologyMasters/jobs#616]
I am currently hiring a Tech Lead on my team at **Immigration, Refugees and Citizenship Canada** . Here are a few details about the job:

- Working remotely
- Working in an Agile environment
- Leading a team of Sr. Developers, Jr. Developers, Sr. QA Testers and QA Testers
- Must be proficient with Angular, Node.js, Java, Kubernetes, and AWS
- Having 5+ years of leading teams, and major projects
- Must have experience in delivering a product to production to the general public

Please send your resume to **Shafiq.Shamji@cic.gc.ca**

**Comment by superwizard03** [comment]
Hello Shafiq, How are you?
This is David Smith from Canada, I have over 5 year of experience in angular 2+ at FE and Node.js at BE.
This is one of my most recent Angular projects. It's based on Angular 10. I am sharing some screenshots with you.

Dashboard Page

![crmgrow-dashboard](https://user-images.githubusercontent.com/97472934/171875228-cbdb4756-5050-41cb-b4ac-f6fed000b52c.png)

Pipeline Page

![crmgrow-pipeline](https://user-images.githubusercontent.com/97472934/171875202-b90d1f90-c2c8-4e79-a5c7-179723f011a2.png)

**Comment by theetrain** [comment]
Closing because issue title does not follow required format: `[Company Name] - [Job Title] - [Location]`, and job description deviates from template too far: https://github.com/TechnologyMasters/jobs/blob/master/.github/ISSUE_TEMPLATE/job.md.
