### ISSUE TITLE
Senior Full Stack Developer - Immigration, Refugees and Citizenship Canada

### ISSUE THREAD

**Issue by ShafiqShamji** [TechnologyMasters/jobs#617]
I am looking for a **Senior Full-Stack Developer** to work on my team at **Immigration, Refugees and Citizenship Canada**
The Senior Full-Stack Developer must be experienced with the following:

- 3+ years of development experience using: Angular 2+, Node.js, and Java
- Providing coaching and development to Junior Developers
- Working with QA team
- Performing User Acceptance Testing (UAT)
- Performing code reviews
- Be a subject matter expert with front-end and back-end technologies
- In-depth knowledge of Angular, and experience with AWS
- Having successfully delivered a product to live production and to the general public

Please send your resume to Shafiq.Shamji@cic.gc.ca

**Comment by superwizard03** [comment]
Hello Shafiq, How are you?
This is David Smith from Canada, I have over 5 year of experience in angular 2+ at FE and Node.js at BE.
This is one of my most recent Angular projects. It's based on Angular 10 and RxJS at FE and Express and MongoDB at BE. I am sharing some screenshots with you.

Dashboard Page

![crmgrow-dashboard](https://user-images.githubusercontent.com/97472934/171876235-700495b4-cce1-452e-96cd-079cf839a628.png)

Pipeline Page

![crmgrow-pipeline](https://user-images.githubusercontent.com/97472934/171876320-a34cffbe-317d-4138-8d29-847d93587da6.png)
