### ISSUE TITLE
FOUNDING ENGINEERS -- for new, London-based stealth B2B tech SaaS startup (£4M pre-seed) - LONDON/HYBRID ONLY

### ISSUE THREAD

**Issue by phwayomnea** [TechnologyMasters/jobs#624]
<aside> **We are currently operating in stealth mode & can share more details over the phone.**

We are lucky to be supported by the two best VCs out there (one European, one US) and 10+ of the most renowned Founders of the last decade, who have invested an initial $5m to help us develop our core product. We are now building out the early engineering team to go on this journey with us & build one of Europe’s fastest growing start-ups!

</aside>

## Mission

The way businesses buy stuff is **completely broken**. Whether it’s SaaS, hardware, or contractors, the average B2B purchase takes over **3 months**, requires **50+ emails**, and involves **multiple different stakeholders** (IT, Legal, InfoSec, Finance, etc.). Omnea is building **one platform** to take the hassle out of the **entire purchasing process**, getting employees the tools they need to get sh*t done**.**

**[*More on our product [[here](http://omnea.co/product)](http://omnea.co/product) (password: engineer10), more info on Omnea [[here](https://www.notion.so/Work-at-Omnea-f08eb0e2bc874a4980e19a0b67928d23)](https://www.notion.so/Work-at-Omnea-f08eb0e2bc874a4980e19a0b67928d23)]***

---

## What is a Founding Engineer?

🛠️  As an early founding engineer, this is a unique opportunity to help build a product from scratch. You’ll be working broadly across **Engineering, Product, Support and People** to implement the vision for Omnea and set the direction for the next 10 years. 

> *A founding engineer is someone who can be the foundation of an engineering team from a technical and cultural standpoint. They set the bar for engineers who join who after them. They also have to be comfortable with the lack of structure and wearing multiple hats (e.g. frontend, backend, devops, talking to customers, etc.). – [[Shin Kim (Eraser)](https://basecase.vc/blog/founding-engineer)](https://basecase.vc/blog/founding-engineer)*
> 

## What can you expect?

<aside>
🛠 **Engineering**

 ****You’ll build a beautiful SaaS application using React & GraphQL from scratch to deploy to tens of thousands of users in a matter of months. You’ll need to write a lot of code. You’ll get your hands dirty with coding, technical architecture, infrastructure, DevOps, product design and everything in between.

</aside>

<aside>
💁 Supporting Customers

You should also expect to spend time in the trenches supporting customers. You’ll probably find yourself engaging with customers in shared Slack, Emails, Intercom to answer product questions, triage bugs, or gather feedback. 

</aside>

***Depending on the person, this role could also include:***

<aside>
⚙ ****Product****

You’ll also have a significant amount of ownership over the product direction. You should expect to spend time interacting with customers and making prioritisation decisions regarding both the short- and long-term roadmap.

</aside>

<aside>
🗣️ People

You’ll be exposed to the people operations side of things as well as defining the culture of the company. As a founding engineer, you will help with hiring & onboarding early team members.

</aside>

> *“For many, the breadth of the Founding Engineer role is the most exciting part of it – getting exposure to things beyond your immediate skill set. There's so much that you will learn through osmosis by just being in the room when it happens. For others, it’s the core engineering side of things that excites them the most & that’s fine too — they’re both different flavours of the Founding Engineer role at Omnea. We believe that diverse backgrounds, interests, and skillsets create the strongest teams.” (Ben Allen, CTO)*
> 

---

## About you

- **You’re experienced (3+ years)** with building beautiful full-stack web apps having designed and implemented features from start to finish using React.
- **You’re product-minded.** You have a sense for a great user experience and feel for when something is off. You like interacting with customers and building for them. You find fulfilment in building beautiful products that people actually love to use.
- **You’re entrepreneurial.** You are excited about the opportunity of being a founding member of the engineering team and taking something from 0 to 1. You know it’s going to take hard work and lots of learning but you are ready to take it on.
- **You’re ready to get a lot done.** You enjoy all aspects of building a product and are comfortable moving across the stack when necessary. You problem solve independently and enjoy figuring stuff out. You’re ready to pick up new skills and build quickly.
- **You’re someone who craves ownership.** A good founding engineer craves ownership. Maybe you find yourself gravitating towards the meatier engineering projects, or even owning the new emplovee onboarding program or volunteering to run a hackathon.
- **You’re high conviction.** When you commit to something, you're in all the way. You're opinionated, but you know when to [[disagree and commit](https://www.inc.com/jeff-haden/jeff-bezos-uses-disagree-commit-rule-to-overcome-an-uncomfortable-truth-about-teamwork.html)](https://www.inc.com/jeff-haden/jeff-bezos-uses-disagree-commit-rule-to-overcome-an-uncomfortable-truth-about-teamwork.html).
- **You’re a** **team builder.** You’re ready to build teams, not just be part of it. You’re happy to take the extra time to explain things, provide actionable feedback, and level up those around you.
- **You’re comfortable when faced with a lot of ambiguity.** Both technically and organisationally. You’re happy to tackle problems without a clear definition or solution. It’s a startup!

*If you don’t meet all of these yet you should still seriously consider applying – we were all missing at least one of these at the outset!*

## How we build...

It’s more important to have the right mindset and ability to resolve problems than your exact experience with certain languages and tools, so don’t let that put you off applying — we often back hunger over experience. That being said, we know that you’ll want to know what technology you’ll be using on a daily basis so here’s the run down:

🔐  **Technologies:**

- NextJS, React, React Hooks, ES6+, Material UI, TypeScript
- NodeJS, GraphQL, Hasura, Docker, Postgres

If you want to chat about Omnea & think you could be a good fit, please contact us at phway.a@omnea.co to arrange a call

**Comment by theetrain** [comment]
Closed because post title does not match our pattern. It should read `[Company Name] - [Job Title] - [Location]`
