### ISSUE TITLE
Software Engineer

### ISSUE THREAD

**Issue by AlphaRecruitingWarehouse** [TechnologyMasters/jobs#633]
### Salary Expectation

- $111,000 - $160,000
- Full Time

### Benefits

- Paid time off: Vacation, Personal, Sick days, and Holidays
- 401k plan with matching
- Full medical and dental insurance coverage
- Pre-tax commuter benefits
- The usual snacks and drinks!

### Location

- East Coast, United States

## What You'll Do _(Job Description)_

The TLC is one of the world's most trusted financial data and research providers in the options markets. They are looking for a few good Software Engineers to join our group. If you are passionate, driven, and eager to learn new technologies...if you love spending weekends with friends and family instead of production support...and the idea of working alongside exceptionally bright and creative developers and quants excites you, we need to talk!

As a Software Engineer, you will have a variety of technologies to work with. Python, Java, C++, Go, JavaScript, they use them all! Their infrastructure is 100% cloud-based, which means you can finally say goodbye to soul-crushing technical debt and hello to cutting-edge tools and tech! You will develop applications accessing large financial data sets. You will be collaborating daily to brainstorm and implement our next generation of data and analytic information products.

At TLC, they emphasize accountability over micromanagement. They invest in their talent with free learning resources like Udemy courses, O'Reilly subscriptions, even pay for conferences and certification exams! They are small, agile, casual (no suits – shoes optional), and passionate about thei mission and the projects they create. As a development team member, you will have true ownership over your projects from beginning to end.

### Must Have

- Have 6+ years of experience with a mix of Java, Python, SQL, and cloud experience.
- Enjoy the challenge of researching data issues to maintain quality in our large data sets

### Nice to Have

- Go
- Vue
- Javascript

### Relevant Experiences

- An understanding of the complex math associated with Options

## About Our company

Alpha Recruiting Warehouse is a boutique recruiting firm for sales and tech companies.

## How to apply

Please send an email to alpharecruiting@protonmail.com with your resume, use 'Software Engineer' as subject

---

## Meta

- [X ] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [X ] Remote Regional
- [ ] Remote OK

**Comment by theetrain** [comment]
Closing because it does not follow the issue title format: `[Company Name] - [Job Title] - [Location]`.
