### ISSUE TITLE
Data Engineer-Analyst

### ISSUE THREAD

**Issue by StartupWhisperer** [TechnologyMasters/jobs#635]
### Salary Expectation

- $120K - $200K dependent on experience and ability - mid/senior/principle levels
- Full Time

### Benefits

- Health Insurance.
- Financial & Retirement
- Performance Bonus
- Maternity & Paternity Leave
- Vacation & Paid Time Off
- Perks & Discounts
- Free Lunch or Snacks
- Professional Support 
- Professional Development
- ...

### Remote regional USA - the Data Engineer-Analyst must reside in one of the following states, due to quarterly meeting in Pasadena, CA) 

ALABAMA - ARIZONA - CALIFORNIA - COLORADO - CONNECTICUT - GEORGIA - MARYLAND
MICHIGAN - MISSOURI - NEVADA - NEW JERSEY - NORTH CAROLINA - TEXAS - VIRGINIA - WASHINGTON - WISCONSIN

## What You'll Do _(Job Description)_

We are looking for a Data Engineer Analyst to join our team and help build our Next Generation customer data management, analytics, and ML platform. This role will work as part of the larger data science and analytics team to build and maintain business-critical data pipelines and infrastructure.

- Design and build maintainable and scalable infrastructure for data extraction, preparation, and loading data from backend services and web browser clients to our data lake and other reporting databases.

- Build and manage tools to monitor pipeline performance and provide deeper insight into pipeline metrics.

- Monitor data pipelines and services for issues and ensure identified bugs are routed and resolved.

- Work with large, complex SQL and NoSQL databases.

- Create and maintain technical documentation and write well-abstracted, reusable, and efficient code.

## What You Need to Be Successful _(Skills)_ 

- SQL & NoSQL databases
- Python programming
- Extensive AWS 
- EMR RDS Redshift Kinesis
- Hadoop or spark environment
- Ruby or Java programming skills 
- Extensive ETL tools
- Data collection tools - Segment Tealium mParticle 

### Must Have

- BS in Computer Science, Information Systems, or equivalent skills and experience
- Minimum 2+ years of experience in data engineering or software development
- Strong competency in SQL and Python programming
- Experience with AWS eco-system and working with services like EMR, RDS, Redshift, Kinesis, etc.
- Experience working with large data sets in a Hadoop or Spark environment
- Strong organizational skills and detail-oriented mindset
- 
### Nice to have in addition to the above

- 5+ years of experience in backend software development
- Strong Ruby and/or Java programming skills
- Experience with and understanding of ETL tools
- Understanding of event data collection tools like Segment Tealium, mParticle, etc.
- 
### Relevant Experiences

- Software development experience in addition to the above

## Company overview
Our client is a people search engine that both enlightens and empowers our customers. With over 12 billion records and 14 million visitors per month, we reconnect friends, reunite families, prevent fraud, and more. 

We are looking for a Data Engineer, Analytics to join our team and help build our Next Generation customer data management, analytics, and ML platform. 

This role will work as part of the larger data science and analytics team to build and maintain business-critical data pipelines and infrastructure.

**COMPANY CULTURE**

Great opportunity for someone looking to be a larger fish in a smaller pond where their suggestions will be listened to and implemented. Have you voice heard!

We support and encourage and learning and growth environment.

We’ve assembled experienced leaders from various industries to lead our teams and build impactful products and services.

From aiding individual volunteers and nonprofit organizations, to employee donations, we are committed to connecting and assisting people through our technology.

We hold ourselves to the following values and beliefs so that we can achieve data and cultural transparency.

Listen with empathy, understand the why, clarify with data, Innovate to learn, collaborate to achieve, insist on quality.

## How to apply

Please send an email to [hunt@empireheadhunters.com) with your updated and correctly formatted resume, and a brief cover letter detailing why you feel that you are the best fit for this role - use 'Data Engineer/Analyst applicant TM' as subject line. 
PLEASE NOTE - applicants must be a US citizen. H1B with minimum 2 years left will be considered if fully qualified. This is a high priority role.

---

**Comment by theetrain** [comment]
Closing because issue title does not follow required format: `[Company Name] - [Job Title] - [Location]`.
