### ISSUE TITLE
Principle AI Engineer 

### ISSUE THREAD

**Issue by StartupWhisperer** [TechnologyMasters/jobs#636]
## What You'll get
- Full relocation package for a rockstar candidate
- MUST be a US citizen (no sponsorship offers at this time)

### Salary Expectation

- Full Time W2
- 170K - 245K USD dependent on experience
- 
- ### Benefits

- DEI & growth culture
- Health & Insurance Benefits
- Retirement & Financial Benefits 
- Paid Holidays / Vacation/Sick
- Casual Dress/Atmosphere

- ...

### Location

- Plymouth Minneapolis, MN, US
- This is an ONSITE role working in Minneapolis, MN (full relocation assistance is available); Possibly Hybrid work (2 or 3 days offsite and 2 or 3 days onsite are negotiable). Hybrid role ONLY if candidate lives locally to Minneapolis, MN area

## What You'll Do _(Job Description)_

- Define and lead computer vision technologies supporting autonomous and unmanned aerial vehicles, and alternative navigation solutions
- Lead Voice of Customer (VOC) activities with key external and internal customers, leading to the development and transition of key computer vision technologies
- Drive technology transitions and productization of key computer vision technologies to develop hardware, software, edge solution and integrate it onto key Unmanned Aerial Vehicles (UAV) and Urban air Mobility (UAM) platforms
- Thrive in a fast-paced environment with rapidly changing priorities that require quick adaptation

### Must Have

- Master’s Degree in Electrical Engineering, Robotics, or Computer Science
- Experience in computer vision, Artificial Intelligence (AI), and Machine Learning (ML) as applied to autonomy and navigation for UAM and UAV applications
- Computer vision, machine learning, navigations for UAM & UAV
- 8+ years managing complex technical R&D programs for internal customers and external government customers such as AFRL or DARPA.
- A proven track record of experience ( pursuing and winning ) government-funded programs
- 3+ years working as a NodeJS developer
- 2+ years working with mongodb; express

### Nice to Have in addition to the above 

- Ph. D in Engineering, Robotics or Computer Science is strongly preferred.
- Experience deploying complex computer vision solutions on unmanned systems for autonomy applications such as automatic landing/takeoff, landmark navigation, visual odometry, optical flow, target tracking or detecting and avoid.
- Publications in top conferences and journals in the area of computer vision and/or machine learning
- Experience with new methods of computer vision including machine learning (especially deep learning)
- Experience working with business leaders to define technology and product roadmaps
- Experience leading technical teams to integrate sensors (e.g., FLIR Blackfly Camera or Ouster LIDAR) and algorithms on embedded platforms (e.g., NVidia Jetson or Xavier embedded GPUs)
- Experience writing DoD proposals, including technical content and developing accurate project cost and resource forecasts
- Team player who can both lead and contribute as the various projects require

### Relevant Experiences
- Candidate should have a Master’s in Engineering, Robotics or Computer Science (but a PhD is preferred) and a minimum of 8+ years of experience in AI (Artificial Intelligence) and deploying complex computer vision solutions on unmanned systems for autonomy applications such as automatic landing/takeoff (VTOL), landmark navigation, visual odometry, optical flow, target tracking or detect and avoid.
- You should have experience as a Technical Lead for the development of computer vision, artificial intelligence (AI) and autonomy technologies for aerial vehicle platforms.
- He / she should have some experience leading top conferences and journals in computer vision and/or machine learning.
- Candidate should have experience with new methods of computer vision including machine learning (especially deep learning).
- He / she should have experience working with business leaders to define technology and product roadmaps.
- Candidate should have experience leading technical teams to integrate sensors (e.g., FLIR Blackfly Camera or Ouster LIDAR) and algorithms on embedded platforms (e.g., NVidia Jetson or Xavier embedded GPUs).
- He / she should have experience writing DoD proposals, including technical content and develop accurate project cost and resource forecasts.
- Pilotless vehicles / urban air mobility / VTOL
- Deep expertise in sensors, systems, navigation, avionics
- Automated landings “safely”
- An architect level to take the product from a vision to production level.
- Drive Teams to develop technologies / yet understands business-speak, someone that “knows” the audience.
- Research of advanced AI
- 
## About Our company

Fortune 100 company that invents and manufactures technologies to address tough challenges linked to global macro-trends such as safety, security, and energy. With approximately 110,000 employees worldwide, including more than 19,000 engineers and scientists, we have an unrelenting focus on quality, delivery, value, and technology in everything we make and do.

## How to apply

Please send an email to [hunt@empire Headhunters.com) with your updated resume and brief cover letter telling us why you fit this role. Use 'Principle AI Engineer application" as the subject line.

---

**Comment by theetrain** [comment]
Closing because issue title does not follow required format: `[Company Name] - [Job Title] - [Location]`.
