### ISSUE TITLE
Intermediate Software Engineer

### ISSUE THREAD

**Issue by JoshuaStewartEntelect** [TechnologyMasters/jobs#638]
### Salary Expectation

- Negotiable
- Full Time

### Benefits

 - Pension scheme with company contribution
 - Life assurance and income protection
 - Generous leave allowance
 - Furthermore, you get to experience the incredible company culture and all it has to offer:
 - Professional and personal growth
 - Training, mentorship, and exposure to lots of different opportunities to experiment and learn.
 - Project variety
 - With a variety of projects using an array of technologies across various business domains, you can find work that suits you.
 - Team-based projects
 - All our projects are team-based, so you're always with other experienced people who will show you best practices and involve you in finding new and innovative ways to do things.
 - Work with like-minded people

### Location

- London, UK
- A hybrid work arrangement

## What You'll Do

We are a tribe of technology professionals who appreciate the skills we bring to the table, help grow each other, deliver awesome solutions using best practices, and have a good time doing it. Engineering track Developing sophisticated software to better the world. The software engineer's role is to engineer the delivery of working software that meets our client's needs. Sounds fancy, right? As a Software Engineer at our company, you are responsible for more than just writing code. You will find that the process, environment, tooling, and even maturity of the client’s software knowledge varies across the teams, so the Software Engineer’s job would vary too, depending on the situation. Being adaptable as a Software Engineer is very important. You will find that as you transition through different projects, teams, domains, and clients, you will always be learning - and that’s part of what makes working at our company cool.

About the role
If you are at this point in your career, it means that you have experience, you are working fairly independently, and are probably becoming everyone's ‘go-to guy'. As an Intermediate, you are expected to be skilled enough that you can assist other Software Engineers. You have a good sense of things like coding principles, and stakeholder engagement and you are a damn good trouble-shooter because you understand how systems fit together, and when and who to ask for help. At this point in your career, you should also be able to architect basic components of a system.-Our UK business is just getting started, so you'll have an opportunity to shape our identity as we grow.

### Must Have

- 3+ years of work experience
- Relevant degree

### Nice to Have

- .NET, 
- Java, 
- JavaScript, 
- Agile

## How to apply

Please send an email to josh211505857@gmail.com with your resume

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [x] Remote Regional
- [ ] Remote OK

**Comment by theetrain** [comment]
Closing because issue title does not follow required format: `[Company Name] - [Job Title] - [Location]`.
