### ISSUE TITLE
BeeBase GmbH - Senior Software Engineer Frontend/Fullstack - Remote/Switzerland (Winterthur)

### ISSUE THREAD

**Issue by nineoh** [TechnologyMasters/jobs#640]
# What You'll get

## Salary Expectation

- Full-Time
- CHF 90'000 - CHF 120'000

## Benefits

- 25 days vacation per year
- Remote working
- Flexible working hours
- Part time possible
- Budget for your own hardware
- Health insurance

## Location
- Mostly remote, occasionally at client's or company's office in Winterthur, Switzerland

# What You'll Do (Job Description)

Together in a team with enthusiastic software developers and designers, you will design and implement exciting projects using the latest technologies. Your solution-oriented approach and your attention to detail enable you to create first-class software. You will also contribute to quality assurance through joint code reviews in the team and automated tests. Last but not least, you are an open, communicative person who enjoys working remotely and also on-site if it's required.

# What You Need to Be Successful (Skills)

## Must Have

- Strong understanding of core architectural and programming principles
- Strong understanding of web technologies and protocols
- Strong skills in JavaScript and TypeScript
- Strong skills in Node.js
- Strong skills in modern JS frameworks like Angular, Next.js or React
- Good understanding of database technologies (SQL, No-SQL)
- Good understanding of Git and CI/CD
- Strong organizational skills and self discipline
- Able to work independently
- Good communication skills
- German C1 or higher required

## Nice to Haves

- Experience working with Kubernetes and orchestration of Docker containers
- Skills in C# and .NET
- Skills in NestJS
- Experience with CRM technologies like Microsoft Dynamics 365 or Salesforce

# About BeeBase

We are a young company that is always looking for new challenges. We make it our task to provide our customers with professional advice and support in the areas of software development and online marketing at a high level. Our culture is clearly characterized by the fresh start-up spirit that has accompanied us from the beginning. A development-oriented management style is our focus, clear structures and processes round off our workflow. Despite our modern premises in Winterthur, we act as a remote-first company and are well positioned and networked. In addition, we want to help shape the workplace of the future through progressive working conditions and a motivational atmosphere.

# How to apply

Please reach out using our recruitment portal at [jobs.beebase.ch](https://jobs.beebase.ch/)

# Meta

- [x] Full-Time
- [x] Part-Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [x] Remote Regional
- [ ] Remote OK

**Comment by smart0815** [comment]
Hello, nice to meet you
How're you?
I have several years of development experience and I’m highly skilled in security, server maintenance, and new feature implementation
I developed multiple websites and web & mobile apps in the business, enterprise, and eCommerce fields
I want to apply the role as soon as possible
I will be available at your time

Thanks
Have a great day

**Comment by nineoh** [comment]
Hi @smart0815, 

Nice to meet you, too!
Please apply via our recruitment portal at [jobs.beebase.ch](https://jobs.beebase.ch).

Thank you very much! :)
