### ISSUE TITLE
Hiive - Senior Full Stack Engineer - Hybrid/Canada

### ISSUE THREAD

**Issue by seanhuggins1** [TechnologyMasters/jobs#643]
### Salary Expectation

- CAD $75K - $170K/yr
- Contract / Full Time

### Benefits

- Competitive salary, commensurate with experience and contribution.
- Health & dental benefits, and a health spending account.
- Option to work remotely or in our office in the Mt. Pleasant neighborhood of Vancouver, BC with a first-class view of the mountains.
- Opportunity to participate in the ownership of a seed-stage startup through our employee stock option plan.

### Location

- Vancouver, British Columbia

## What You'll Do _(Job Description)_

As a Senior Full Stack Engineer at Hiive, you will report to the CTO, and work directly with the executive and founding team to deliver core features of our application, create a robust, scalable, and secure infrastructure, and continue to build out the market for the product.

Hiive is looking for a Senior Full Stack Engineer to join the product team to work on a platform utilizing an Elixir Phoenix GraphQL backend API and React.js/Typescript on the frontend.

## What You Need to Be Successful _(Skills)_

**A great candidate would…**

- Consider themselves highly capable of hands-on development of API and asynchronous functionality for processing data and workflows in a complex system.
- Consider themselves highly capable of hands-on development of a mobile responsive user interface with React and Typescript from day one.
- Know the ins and outs of data modeling and software architecture for developing performant and maintainable code.
- Have experience with integrating with third-party services through APIs and webhooks alongside local data processing.
- Be well versed in all aspects of secure API development.
- Be well versed in all aspects of frontend development including styling, performance, responsiveness, and in creating reusable components.
- Be comfortable working with a very small team including directly with the founders on building a product and a company.
- Adapt well to a quickly moving environment.

### Required Experience:

Backend Development
- 5+ years of experience in developing backend services with APIs and relational databases.
- Experience with the Elixir programming or similar experience and a desire to learn Elixir.
- Able to work in a team environment with a CI/CD driven workflow.
- Have a philosophy in writing automated backend tests.

Frontend Development
- 3+ years of experience in building interfaces with React or similar technology.
- Previous experience of working in Typescript.
- Experience with component libraries (such as Chakra UI).
- Translating from Figma, or similar, design files into implementation details.
- Working closely with designers on feedback for designs and implementation tweaks.

### Preferable Experience:

- Experience in making GraphQL APIs and Apollo Client.
- Understanding of Postgres databases design and optimization.
- Knowledge of Elixir, Phoenix, and Absinthe.
- DevOps know-how, specifically deploying and configuring AWS services.
- Data reporting with SQL and dbt.
- Experience with Vercel & Next.js.
- Using Terraform for deterministic infrastructure definitions.
- Fintech and/or marketplace experience.

## About Our company

Hiive is a fintech startup, backed by seasoned professionals with decades of experience in private equity and capital markets. The company is building a revolutionary product for buyers and sellers of shares in private pre-IPO companies and “Unicorns,” bringing a rational, beautiful and modern technological interface to a messy and traditional market.

## How to apply

Apply via Linkedin

https://www.linkedin.com/jobs/view/3190258808/?refId=bV80CDEbZkO%2FoDOk8rSDGw%3D%3D&trackingId=t0u05IyHOIUtmPr3N%2FtPEQ%3D%3D

Or email: vitor@hiivemarkets.com

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [x] Remote Worldwide
- [x] Remote Regional
- [x] Remote OK

**Comment by Alanmiller11** [comment]
"Hey , I hope you are doing well!

I'm Alan from Ninja Tech.  We work with startups & SMEs for providing the Team. I have gone through your requirement and we do have the bandwidth for the technologies you are looking to hire experienced resources for. 

Our Focus is to provide a dedicated Team and resources and we do have a dedicated website for the same: https://thelevelup.team/

It would be productive if we can connect for a quick meeting at your convenient time today. Please let me know what your schedule may allow. "
