### ISSUE TITLE
Kemet Trading - Senior Software Engineer - Remote US

### ISSUE THREAD

**Issue by Ashmawy** [TechnologyMasters/jobs#645]
## **Senior Software Engineer**

**Company Overview**

Kemet Trading is building crypto-derivative trading infrastructure for institutions to eliminate fragmentation around liquidity, data and compliance/workflows across both TradFi/DeFi. Founding Team from D.E. Shaw & CO, Tradeweb Markets, AWS and ZealPay. We’re backed by some of the biggest names in digital asset trading and VCs such as LedgerPrime, Csquared Ventures, Genesis, BECO capital, Flow Traders and a host of some of the best angels/operators in the industry.

**Role Overview**

Kemet is looking for a product-minded senior full stack software engineer to help the team build our crypto-derivatives trading platform. You will work with software engineers, leadership, product managers, and other engineering team members to design and implement frontend components and backend services as well as cloud infrastructure changes and CI/CD pipelines. You must have a passion for designing and building distributed highly-scalable complex software and writing production quality code.

**Essential Job Functions**

- Design robust, secure, highly-scalable, and distributed systems.
- Building complex software with an emphasis on performance, scalability, security, and high-availability.
- Building React frontend components and service-side Node.js services in TypeScript.
- Writing unit and integration tests
- Performing code reviews, design reviews, and writing documentation.
- Containerize their code and deploy containers to Kemet’s production and non-production environments using CI/CD pipelines.
- Help managing Kemet’s cloud infrastructure on AWS, and run operations including but not limited to logging, alarms, monitoring, and fixing production issues (you build it you own it).

**Minimum Qualifications**

- 5 years of experience in software design/development and/or operations.
- Strong object oriented design and development skills in TypeScript or, JavaScript
- Expert knowledge with SQL and NoSQL databases (PostgreSQL, DynamoDB, MongoDB, etc)
- Expert knowledge in server-side web and API development (REST, WebSockets, GrahpQL) using Node.js.
- Experience in front-end development and building Single Page Apps using a modern JavaScript framework (React, Next.js, Vue, Angular) incl. HTML5, CSS3. React.js is highly desirable.
- Experience working on an Agile team, writing clean code and utilizing pair programming, TDD, continuous integration and code reviews.
- Unit testing experience is a must, TDD is a plus (Jest, Jasmin, etc.)

**Nice to have:**

- BS degree in Information Systems or Computer Science or a related technical discipline, or equivalent practical experience.
- 7 years of experience in software design/development and/or operations.
- Experience in CI/CD (Git, Gitlab, Jenkins, Containers), knowledge in other DevOps practices is desirable (IaC, Terraform, Cloud Formation).
- Experience with AWS or other cloud service providers.
- Experience designing and building large scale distributed Microservices architecture based on 12-factor app guidance. Cloud-native, Serverless architectures experience is highly desirable.
- Experience using tools like Jira, GitLab.

**Benefits**

- Competitive Compensation Package (Base salary + equity)
- Health & Wellness: medical, dental, and vision insurance plans for employee and dependents.
- Unlimited PTO: Unlimited vacation policy for strong, fully charged batteries.
- Remote work and flexible hours
- HSA, FSA, & DCFSA: Pre-tax savings plans for healthcare and dependent care.

**How to apply**
Please send your resume to aelghobary@kemettrading.com or apply directly on [LinkedIn](https://www.linkedin.com/jobs/view/3201714580)

**Comment by adilwahla** [comment]
I am hoping to to work with Professional Crypto Trading company from some of the best in the industry, and in my research, I came across  Kemet Trading . Our goals and interests are so aligned, I think we’d both accomplish more if I took my research and resources to your company.

Here is my App/web profile [https://brahimfords.com/].

I’d love for an opportunity to meet and talk further about how we may work together.
Sincerely,

Adil Rehman
adilwahla360@gmail.com
Software Engineer
