### ISSUE TITLE
CFD - Web Developer freelance WP/Shopify - location independent

### ISSUE THREAD

**Issue by JessicaAudsley** [TechnologyMasters/jobs#647]
## What You'll get

Careful Feet Digital (CFD) is a full-service digital marketing agency growing by leaps and bounds. Our business model is unique: we are a distributed team of digital marketing experts who work on projects for clients worldwide. We serve all types of industries, including e-commerce, aeronautics, education, tech and B2B, on a variety of digital marketing projects, including social media, PPC, SEO and content marketing. Founded in 2018, CFD is proud to be an award-winning agency that helps businesses of all sizes find and share their voice online.

You’ll work with a small dedicated team on client projects. You need to be comfortable working in an asynchronous, digital-first environment without a lot of direct supervision. You must be able to take ownership of your tasks from start to finish, understanding not only the tasks but the strategy behind them. You may be asked to join a client call from time to time.
You can work anywhere you want to- that’s part of the CFD ethos and mission. You can make your own hours, as long as you’re generally available for check-in calls and other synchs as required (these are typically weekly). All other communication can be through email and Slack.
Most of our team check-ins are on Slack or Google Hangouts, and projects (clients and internal) are managed using Asana. We expect our team members to attend team meetings and contribute to the culture of the company as well as participate in client-facing tasks. We expect responses to queries within 24 hours and for you to be available on Slack within 24 hours of a message.

To us, mindset and a willingness to learn is everything. If you’re a positive go-getter and team player with great communication skills, you’ll make a great asset to our team!
You need to have prior freelancing experience and even better if you’ve worked with agencies. Of course, web development is a must, which you can demonstrate through your application and if you are shortlisted, through our skills quiz for this role. We are also looking for someone who is able to make a commitment to our team, as we’ll commit to working with you. We have high expectations, and we’re not going to say otherwise- we invest in our team members and make meeting those expectations worthwhile.

### Salary Expectation

-   Please supply your hourly rates in your application.

## What You'll Do _(Job Description)_

We are looking for a freelance web developer, perhaps you are a digital nomad or simply enjoy freelancing, to take on website management for some of our US and UK-based clients. In addition, you will be responsible for our agency website and the necessary updates.
www.carefulfeet.me
 
 In addition we are looking at a domain swap which you would be implementing and driving with the support of a project manager.
The role requires approx. 40 hours per month with a 3-month probation period. 

## What You Need to Be Successful _(Skills)_

Role requirements
The type of tasks you will be required to do include, but are not limited to:
● Perform ongoing website management for agency clients with platforms on Wordpress, Shopify, Wix, Squarespace and Square Manage and develop our company site, carefulfeet.me (Wordpress)
● Comfort with front- and backend updates, including moderate front end design changes that would come out of UX, CRO and design/brand audits
● Analyze performance and confidently communicate suggested amendments to site in order to achieve best site performance possible
● Develop, evaluate and optimise landing pages
● Write well designed, testable, efficient code by using best software
development practices
● Create website layout/user interface by using standard HTML/CSS practices
● Integrate data from various back-end services and databases
● Gather and refine specifications and requirements based on technical
needs
● Create and maintain software documentation
● Be responsible for maintaining, expanding, and scaling our site
www.carefulfeet.me
 
 ● Stay plugged into emerging technologies/industry trends and apply them into operations and activities
● Cooperate with web designers to match visual design intent where a web designer is available - sometimes this is you!
● Knowledge of Wordpress, Shopify, Squarespace, Wix, Square, Github and Google Analytics
You must be comfortable working with others in a fully digital team. You will be expected to answer client questions if needed for some of the larger projects you will work on, although there will always be an account or project manager to support you on those.
Since we are a small agency, there may be client and internal tasks that are required outside the scope of this job description. This role is only appropriate for people who are interested in and happy to be a team player and help shape CFD..

## About Our company

We think our way of working is pretty awesome. As we said earlier, you can work from anywhere, at pretty much any time- as long as you deliver on time and well: that’s all we ask of you. We’re a remote team: part time and full time members, which means you can also take on other work, as long as you get your tasks done on time and well, we’re happy if you’re happy with your work/life balance and working environment.
CFD is committed to transparency and growth, and although we don’t work side-by-side in person, we stay in touch via Slack, Asana and e-mail. We’re always looking to get better at what we do, so CFD also gives its staff opportunities to enroll in further education, and will pay some or all of the tuition if it makes sense to help you grow in your career.

## How to apply

Please visit our website to fill out the application: www.carefulfeet.me/jobs

---

## Meta

<!--
  These meta tickboxes automatically apply labels to your post
  Learn more in the README https://github.com/TechnologyMasters/jobs/blob/master/README.md#label-definitions

  Note, you must fill in the checkboxes correctly in order for them to appear as checked in Markdown

- 
- [x ] Part Time
- [x ] Contract
- [ ] Internship
- [x] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by superwizard03** [comment]
Hi, thanks for job posting.
This is Jaxson Lee from Canada. I can not access to the job application link.
www.carefulfeet.me/jobs

Thank you.

**Comment by superwizard03** [comment]
Actually I am very interested in this job post.
I look forward to hearing from you soon.

Thank you.

**Comment by JessicaAudsley** [comment]
> Hi, thanks for job posting. This is Jaxson Lee from Canada. I can not access to the job application link. [www.carefulfeet.me/jobs](http://www.carefulfeet.me/jobs)
> 
> Thank you.

Hi Jaxson,

Please send your application through here: https://docs.google.com/forms/d/e/1FAIpQLSe7LfIpqq8Qgpv3aKylL3KAUeOa0xuV7K3X-bX6snchKmk9-A/viewform?pli=1

**Comment by JessicaAudsley** [comment]
> The application form requires to be signed into Google. Please make it public and allow anyone to enter their information.

Hi there,
It should be public now. Thank you for your feedback.

https://docs.google.com/forms/d/e/1FAIpQLSe7LfIpqq8Qgpv3aKylL3KAUeOa0xuV7K3X-bX6snchKmk9-A/viewform?pli=1
