### ISSUE TITLE
theScore - Engineering Manager - Remote (US and Canada)

### ISSUE THREAD

**Issue by hughie-coles** [TechnologyMasters/jobs#649]
### Benefits

- Ship features that impact millions of users.
- Work on large distributed systems spanning public cloud and on-prem locations.
- Learn how to manage workloads, at scale, running on Kubernetes
- Contribute to a federated GraphQL API used by millions of clients.
- Comprehensive Benefits package.
- Education and conference reimbursement.
- A/V club, Friday presentations, book library, and more.
- Top of the line office hardware

### Location

Fully Remote, open to US/Canada

## What You'll Do _(Job Description)_

We need a senior NodeJS developer that....

### Must Have

- A solid foundation in computer science, with strong competencies in data structures, distributed systems, and software/system design.
- Minimum 3-5 years in a leadership or management role  combined with at least 8 years of experience in software development.
- Demonstrated time management, project management and problem solving skills.
- Ability to communicate complex technical information to various stakeholders, including non-technical members of the organization.
- Excellent presentation and communication skills.
- Demonstrated collaborative work style with the ability to effectively collaborate and work with all levels of the organization.
- Ability to follow through and complete overlapping projects while adhering to strict deadlines.
- High level of critical and logical thinking, analysis, and/or reasoning to identify underlying principles, reasons, or facts.
- Excellent teamwork and team building skills with a proven ability to delegate.
- Experience with modern framework and API development (Ruby on Rails, Phoenix, Node, Django, etc).
- Experience with background job processing and messaging systems (Kafka, Oban, Sidekiq, Celery, Beanstalk, RabbitMQ).

### Nice to Have

- Elixir
- Building GraphQL APIs (Absinthe)
- GraphQL schema stitching & subscriptions
- GCP
- Kubernetes
- Public speaking
- Contribution to open source software
- Experience working at startups
- Passion for sports and/or esports.

## About Our company

[theScore](https://www.thescore.com/), a wholly-owned subsidiary of [PENN Entertainment ](https://www.pngaming.com/), empowers millions of sports fans through its digital media and sports betting products. Its media app ‘theScore’ is one of the most popular in North America, delivering fans highly personalized live scores, news, stats, and betting information from their favorite teams, leagues, and players. theScore’s sports betting app ‘theScore Bet Sportsbook & Casino’ delivers an immersive and holistic mobile sports betting and iCasino experience. theScore Bet is currently live in the Company's home province of Ontario. theScore also creates and distributes innovative digital content through its web, social and esports platforms.

As part of the theScore team, you will be working with a team of smart, friendly, and dedicated Engineers, Product Managers and Designers determined to deliver some of the best apps the market has to offer. We want you to be challenged and to get the full experience of what it’s like to work at theScore!

## How to apply

The following Link https://www.scoremediaandgaming.com/jobs/?gh_jid=4378333004 ,  or if you'd a referral, DM me here and I can refer you directly.

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [x] Remote Regional
- [x] Remote OK

**Comment by smart0815** [comment]
Hi, nice to meet you
How're you?
I checked your description and it's exciting for me
Over 7+ years of experience designing and hand-on implementation of user experiences of applications using HTML, CSS, JavaScript, Python, Nodejs
Experience in all phases of SDLC like Requirement Analysis, Implementation, and Maintenance, and extensive experience with Agile and SCRUM.
I want to discuss this opportunity and please have a schedule
I will be available at your time

Thanks
Have a great day

**Comment by hughie-coles** [comment]
Hey, happy to chat. Please email me at ***@***.***, and I'll
set up a chat with you this week.


Hughie
