### ISSUE TITLE
Stride - Engineering Manager, Platform - Remote (US)

### ISSUE THREAD

**Issue by kathydragone** [TechnologyMasters/jobs#650]
Today, 60 million Americans work independently, and that trend is only accelerating. But benefits are tightly coupled with full-time, W2-based jobs. As a result, the millions of Americans who work independently are excluded from that financial safety net.

Stride is the world's first benefits platform built specifically for contractors, part-timers, and the self-employed. We provide them all the same benefits you'd expect from a W2 job, like insurance, tax support, and discounts on products and services. In fact, since launching in 2014, Stride has helped more than 3 million Americans save more than $3 billion.

We're partnered with the top employers of non-benefited workers, including DoorDash, Uber, Postmates, MasterCard, Amazon, Aon, and Willis Towers Watson. We're backed with over $96 million in capital by Venrock, New Enterprise Associates, Fidelity's F-Prime Capital Partners, King River Capital, Mastercard, and Allstate.

At Stride, we pride ourselves on a snappy, best-in-class User Experience while shopping and enrolling in benefits. While we started with Consumer, other companies in our space started knocking on our door to build a Platform so they could provide their customers with the same experience. Fast-forward to now, and Platform has made us become a hyper-growth company.

We're growing not only in scale but also in team size. For that reason, we're seeking an Engineering Manager to lead and scale our Platform Services team, the foremost Product Backend engineering team at Stride. You will be responsible for recruiting and retaining engineering talent and building an organization that goes beyond just one squad. Platform Services is at the heart of Stride's Product Engineering, and you'll be interfacing with our full-stack teams daily, managing dependencies and crafting roadmaps alongside our Product leaders.

**Responsibilities**

-   Lead, manage, and grow a team of high-performing Platform Backend Engineers.
-   Own the technical direction of the entire set of Platform Services - be responsible for consistently delivering iterations to existing APIs, workers, event-based pipelines, cloud stacks, and building new ones.
-   Ensure that our teams follow Engineering best practices - sprints, code reviews, software design docs, or conducting post-mortems.
-   Set consistent standards for technical excellence, and lead your team to do the same.
-   Set goals for your team and its members. Delegate, mentor, and deliver results.
-   Collaborate across Engineering / Product / QA / Design to deliver features that satisfy customers' needs with simplicity, consistency, and robustness.
-   Balance tradeoffs between practical, incremental release mentality with long-term architectural considerations.
-   Develop a robust engineering-driven culture that promotes diversity, innovation, and creative problem-solving

**Qualifications**

-   3+ years of experience leading consumer-facing backend engineering teams, including performance management.
-   5+ years of hands-on development experience using Node, Express, RESTful APIs, SQL databases (Postgres), including code reviews and driving architectural standards. 
-   We'll also love if you're proficient in any/all of AWS, Typescript, GraphQL, NoSQL (DynamoDB), event-driven architectures (EventBridge), and infrastructure-as-code (Terraform).
-   Recent experience growing high-performing engineering teams in a startup environment, including attracting, hiring, and retaining top engineering talent.
-   Proven track record of managing project roadmaps from conception through successful release.
-   Excellent verbal and written communication skills. Effective communicator at all levels.
-   Prior experience managing a geographically distributed engineering team is highly preferred.

https://www.stridebenefits.com/careers-posting?gh_jid=4303506004

**Comment by WaajidahCrypto** [comment]
Nice
