### ISSUE TITLE
Senior Software Engineer (C#)

### ISSUE THREAD

**Issue by ElyssaHa** [TechnologyMasters/jobs#666]
**At [TripStack](www.tripstack.com) We are travel tech entrepreneurs, changing the way millions of people travel..**

We are looking for a Senior Software Engineer to join our development team. You will be responsible for writing code for a large-scale distributed system, APIs that provide unique travel (flights and more) content to our customers. We are looking for someone who is a natural problem solver, that is detail-oriented and can work both independently and collaboratively in a fast paced environment. This role will help with planning, developing, testing, and deploying our EFOE API. We are looking for someone who is extremely detail-oriented and can work both independently and collaboratively in a fast-paced environment.

**Responsibilities**:

• Design, write, review code for reliable, high-quality systems at scale serving 100s of millions of requests daily

• Evangelize Tripstack products internally and externally

• Proactively identify technology opportunities for the company, and push technical ideas, proposals, and plans to the entire organization and beyond

• Be responsible for good quality code with emphasis on test driven development and clean code

• Work cross-functionally with product managers, data scientists, to deliver high quality products.

• Actively mentor the team on new and existing technology used within our product landscape.

**Desired Skills and Experience:**

• Bachelor's degree or higher in Computer Science or related technical field

•5+ years of experience in C#, .Net (would be considered an asset) Java, Golang, and Python would also be acceptable

• 5+ years of experience and understanding of CS fundamentals including data structures, algorithms, and complexity analysis (time and space)

•5+ years of experience and understanding databases such as Postgres

• 5+ years of experience and understanding of highly scalable caching/no-sql offerings like Redis, Bigtable, DynamoDB.

• 1+ years of experience and understanding of event processing platforms like Apache Kafka

• 2+ years of experience building large scale, high-performance systems in a complex, multi-tiered, distributed environment

• 5+ years of design and architecture knowledge as well as familiarity with object-oriented analysis and design patterns (OOA/OOD)

• Proven track record of taking ownership and successfully delivering results

• Proven track record of designing/architecting scalable, high availability distributed systems that serve internet traffic direct to consumers or businesses at scale (100s of millions of requests per day)

• Experience with Restful API development

• Experience working in a UNIX/Linux environment

• Understanding of performance trade-offs, load balancing and operational issues

• Ability to clearly and concisely communicate with technical and non-technical stakeholders across all levels of the organization

**Comment by theetrain** [comment]
Please provide a location and update the title accordingly. Sample:

```
[Company name] - [Job title] - [Location]
```
