### ISSUE TITLE
Software Engineer - Toronto

### ISSUE THREAD

**Issue by ElyssaHa** [TechnologyMasters/jobs#677]
We are looking for a couple of Senior Engineers to join our team.
DOWNTOWN TORONTO / HYBRID 

- C# / .NET Core focused,  Golang, Swagger, Java, Golang, and Python would also be acceptable

If you are interested, please reach out elyssa.hassanali@tripstack.com
Learn more about us at www.tripstack.com

**Comment by MichelleRadu** [comment]
Hey Elyssa,

I am part of Index - https://remote.index.dev/, a tech-recruitment platform that provides high-performing senior developers. We have a few available Senior Engineers with relevant background. Would you be interested in taking a look at a few CVs? If yes, please ping me back.
