### ISSUE TITLE
Clockwise - Sr Backend Engineer, Growth & Monetization - Remote or San Francisco

### ISSUE THREAD

**Issue by devakone** [TechnologyMasters/jobs#682]
### Salary Expectation

- USD $160,000 - $230,000/year + equity
-  Full Time

### Benefits

- Competitive total compensation package with generous equity
- Premium medical, dental and vision plans
- 401(k) plan
- Wellness stipend
- Virtual happy hours & events 
- Generous, flexible vacation policy
- Paid maternity and paternity leave

### Location

Clockwise is committed to a work experience that exemplifies our values-driven culture and this starts with empathy for everyone who joins our team. To this end, Clockwise offers both fully-distributed and flexible in-office options for new employees.

Fully Distributed: Clockwise has adopted remote-first rituals and technology for all employees in order to create an excellent employee experience for those who opt to work fully-distributed. This extends not only to a stipend for your home office, but through all our company rituals, including a commitment to get together, in person, on a regular cadence. Please note that we’re open to employees located anywhere in the domestic United States.

In-Office: For those who wish to have a physical office to return to, we also offer a flexible option to work from our San Francisco HQ. We have a beautiful, fun, spacious office where everyone can work productively and collaboratively. Our San Francisco HQ is located in the Financial District, a block from the Montgomery Street Muni & Bart station.

## What You'll Do _(Job Description)_

Clockwise is looking to hire a Back End Engineer to join our Growth & Monetization engineering squad. We value engineers who build for the end user, and are passionate about enabling our business to accelerate and scale. This role will be primarily focused on supporting the backend aspects of our experimentation strategy, which includes web based growth experiments, A/B tests and new feature rollouts. You will participate in engineering growth efforts within a squad in partnership with other engineers, a PM and a designer. We're a humble, fast-moving, and fun team building a consumer-centric culture with empathy, authenticity, focus, drive, curiosity, and enthusiasm.

## What You Need to Be Successful _(Skills)_
- Architect back-end systems that significantly impact user acquisition, activation, and retention
- Ship features and improvements focused on user growth
- Brainstorm and implement new experiments that drive direct revenue impact in collaboration with our Product Manager.
- Be a bridge between engineering and marketing
- Contribute to an intelligent time management system that puts time back in people's day
- Commit and push code every day
- Collaborate on design and UX with people who love product
- Directly influence our Growth feature roadmap
- Contribute to our process and technology optimization

### Must Have
- Java or similar
- Postgres or similar
- Kubernetes

****
- 6+ years working as a backend developer

### Nice to Have
- Node, 
- Typescript, 
- Relay, 
- GraphQL

### Relevant Experiences

- Growth & Monetization
-Payments and Billiong

## About Our company

The most important time on our calendars is the space between meetings. Clockwise is a new way of working designed to take back those precious moments—and free up more time for ourselves every day—so we can feel present when we’re working together and focused when we’re working on our own. 

Clockwise learns about the things that matter to us and to our coworkers and makes time for both, using AI to find the right moments for people to meet while saving focus time for each of us. That’s what a sustainable future of work looks like. And that’s what every day at Clockwise looks like.

We can’t fix our schedules on our own. But we can build the solution together. Join us, and let’s rework the workday.

We're proud to have the backing of Coatue, Accel Partners, Greylock Partners, Bain Capital Ventures and other preeminent investors. Our team has decades of experience from places like Twitter, Asana, Salesforce, Dropbox, Meta, Stripe and Google. Join us to help the world make time for what matters.

## How to apply

Please send an email to [email@email.com](email@email.com) with your resume, use 'Node Developer' as subject

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [x] Remote Regional
- [ ] Remote OK

**Comment by MichelleRadu** [comment]
Hello,
We have some available Senior Backend Engineers with relevant background. Would you like to check 2-3 CVs of our top talents?
