### ISSUE TITLE
WG2 - Frontend Developer with an eye for design - Norway, Sweden (remotely Europe)

### ISSUE THREAD

**Issue by marietta-wg2** [TechnologyMasters/jobs#686]
### THE TEAM AND YOUR ROLE 

**The ecosystem and the product team**

We are establishing a new team within our Product Ecosystem domain. This team will be responsible for the development of our Customer Portal. 
The domain today consists of eight engineers, a product designer, a UX researcher, and a product manager, building and developing our ecosystem infrastructure and UI services. We are a remote-friendly and distributed team with most members located in Trondheim, Norway. All current members are within one hour of the CET time zone (UK, Denmark, France). For better team dynamics we believe that the person we hire also should live within the same time zone. 
We do daily morning stand-ups, retros every other week, and backlog grooming when necessary. And that’s it! 
We’re open to adjusting the way we work if you have any suggestions that you think could make it better.

**The position**

We are looking for a confident and strong Frontend developer with an eye for details and design, and with great interpersonal and communication skills. 
You will oversee and drive the frontend development on our new Customer Portal. 
You are capable of implementing solutions that are user responsive and efficient, across a variety of use cases and technologies. 

We need you to translate and implement designs and wireframes into high quality code/ or build new solutions from scratch, and to do so, you will spar with our designer, user researcher and product manager. 

We expect you to be very comfortable with **CSS, HTML, and JavaScript.** 
We use **Vue**, but if you’re more experienced with React, we don’t think that will be a problem as long as you are willing to switch to Vue:)

The position is primarily frontend oriented, but you can also write some web controller code if you want to. Our servers are written in Javalin/Kotlin, which is very similar to Express/Typescript, so if you’re familiar with that as well, it shouldn’t be a problem.

Ultimately, your work will have a direct impact on the user experience of our customers!

Most of our projects use the following technology:

Frontend: Figma, HTML, CSS, JavaScript, Buefy, Vuetify, Vue, Cypress
Backend: Javalin, Kotlin, JOOQ/SQL, K8S, AWS

Salary range depending on the experience / negotiable 

### OUR COMPANY CULTURE 

We’re a challenger in a well established multi-billion dollar industry. To succeed as a company, we need to deliver the high quality core services that subscribers are used to, while also adding value through the way that we operate. We believe our people and our culture will be a key differentiator in achieving this.

If you join us, you’ll get the trust and freedom needed to make a big impact in the telco industry. Since we’re solving telco problems in a modern way, we recruit from various industries and have people that used to work at Telenor, Google, Microsoft, Spotify, and AWS. We promise that you’ll be surrounded by friendly, motivated and highly skilled coworkers. We have a culture of transparency and openness, and oftentimes we call ourselves a “start-up for grown-ups”. We know where we’re going, and with a lot of trust in each other, we’ll pave the way there together.

We’re a distributed company with offices in Oslo, Trondheim and Stockholm, as well as some remote colleagues in other locations (a total of 12 countries). We’ll pay for your phone and internet, as well as your lunch and office snacks. We’ll even pay you for your work! The Covid-19 pandemic forced a lot of companies to change how they think, but for us it confirmed that our remote-friendly and transparent approach goes a long way. We frequently host company wide activities online, like tech talks, demos, and failure fridays. During covid we replaced our quarterly offsites with online HackDays. We also have Monday-kick offs, virtual lunches and fikas, and online gaming groups to keep the workday fun.

### WHAT’S NEXT?

If you’re interested in working with us, please apply through [the link](https://www.wgtwo.com/careers/job/592326/frontend-developer-with-an-eye-for-design-product-team/), or contact Theresa for any questions on Theresa@wgtwo.com.

**Comment by kspaans** [comment]
We require a salary range in our job postings. Please add a salary range.

**Comment by marietta-wg2** [comment]
> We require a salary range in our job postings. Please add a salary range.

it's been added now, thank you for the comment
