### ISSUE TITLE
Barometer - Senior Data Engineer - Remote - 130-150K USD/Annual

### ISSUE THREAD

**Issue by kathydragone** [TechnologyMasters/jobs#689]
Senior Data Engineer (Remote - US)

About Us:
Barometer is an AI powered platform for contextual targeting and brand suitability in audio advertising. We help advertisers align with the perfect podcasts for their ad campaigns and we make it easier for publishers to educate buyers on their content. We are an early-stage, venture backed startup going through rapid growth in customer traction. http://www.thebarometer.co/

We are seeking a Senior Data Engineer to join our team and help us scale our development to meet the demand of our customers. 

About the Role:
As our Senior Data Engineer, you will be responsible for managing our data flows and ensuring the reliability, scalability, and security of our data infrastructure. You will work closely with our full-stack and AI engineers to design and implement data pipelines, ETL processes, and distributed systems that support our business needs. You will also be our first data engineering hire, and will have the opportunity to shape our data architecture and set best practices for the team.

Responsibilities:
Design and implement data pipelines, ETL processes, and distributed systems using SQL, Python, and AWS technologies
Ensure the security and integrity of our data infrastructure by implementing SSL throughout our apps and data pipelines
Collaborate with leadership and engineering teams to define data requirements and design efficient data models
Monitor and optimize the performance of our data infrastructure to ensure reliability and scalability
Build and maintain data processing workflows that support our business needs
Develop and maintain documentation for our data infrastructure and processes
Stay up-to-date with emerging data technologies and best practices, and provide guidance to the team on new tools and approaches

Qualifications:
5+ years of experience in data engineering, with a focus on designing and building data pipelines and ETL processes.
Expertise in SQL and Python, with experience using AWS technologies such as Redshift, S3, Lambda, and EC2.
Strong understanding of distributed systems and experience building scalable and fault-tolerant systems.
Experience with data modeling and database design, including both relational and NoSQL databases.
Strong analytical and problem-solving skills, with a passion for working with data and driving insights.
Experience building and working with RESTful APIs, including familiarity with Swagger, Postman and Stripe API preferred.
Excellent communication skills and ability to work collaboratively in a fast-paced, agile environment.
BS/MS degree in Computer Science or a related field is preferred, however suitable and equivalent work experience in data engineering will also be considered.

Our Current Tech Stack:
Backend: Node.js, TypeScript, EC2, ECR, SageMaker, Tsoa, Swagger
Database: MySQL, DynamoDB, S3
Frontend: React, TypeScript, MaterialUI
Our tech stack will evolve and change over time as we build more things - we're looking for folks with experience in equivalent technologies.
Compensation: $130,000 - $150,000/DOE
Benefits & Perks:
Barometer provides a number of benefits to help you bring your best self to work:
Competitive Compensation
Generous early stage equity packages
Health, Dental, Vision and Life Insurance options
Flexible and fully remote work schedule 
Unlimited PTO
Technology and Home Office Allowance
Optional office space available in Chattanooga, TN and NYC
Sponsored Company Retreats

Barometer is an equal opportunity employer and does not discriminate against any employee or applicant for employment based on race, color, religion, national origin, age, gender identity or expression, sexual orientation, marital status, disability, veteran status, genetic information, or any other protected status under applicable law. We are committed to promoting diversity, equity, and inclusion within our organization and in the communities we serve.

At Barometer, we are solving some of the hardest problems imaginable and do not take our jobs lightly.  As our AI detects everything from hate speech to mensions of adult content, terrorism, and obscenity, please make sure you are aware that we work with potentially emotionally distressing textual data before applying. 

Please Note: US work authorization is required for this position. We are unable to provide visa sponsorship for this role.

To apply: Send your resume to kathy@thebarometer.co.

**Comment by Kucherushka** [comment]
Hello Kathy,
I see you are looking for Senior Data Engineer (remote - US). We here at Talmatic.com have got a few candidates that fit your profile. They are located in Western Europe. Once you decide to extend the hiring geography - we shall send you vetted candidates in 48 hours with the rates 40% lower than traditional hiring methods. Feel free to reach out in any case  - our contact mail hc@talmatic.com.
