### ISSUE TITLE
Sticker Mule - Software engineer (Backend) - Remote Worldwide

### ISSUE THREAD

**Issue by ejmudi** [TechnologyMasters/jobs#691]
### Salary Expectation

- $135k+ (USD) per annum
- $20,000 signing bonus
- 4 weeks vacation + holidays based on your country of residence
- Full Time

### Location
- Remote Worldwide

## Responsibilities
- Improve and expand our GraphQL APIs
- Migrate a large Rails code base to NodeJS services
- Maintain optimal back-end performance

### We like you to know

- Docker
- Ruby
- Rails
- TypeScript
- NodeJS
- GraphQL
- Postgres
- Redis
- Familiarity with React
- Excellent communication skills (English)
- Degree in Computer Science or equivalent practical experience

## About Our company

**Sticker Mule is the Internet’s best printing company**. We support thousands of customers by hiring the best people in the world. Our team works from 17 countries in 4 continents and is united by a desire to do great work while maintaining a stress-free work environment that’s designed to attract like-minded people who enjoy our culture.

## How to apply

[https://jsjobbs.com/javascript-jobs/IcPZfQrekcitS-engineer-backend-sticker-muletm?ref=tm](https://jsjobbs.com/javascript-jobs/IcPZfQrekcitS-engineer-backend-sticker-muletm?ref=tm&utm_source=slack&utm_medium=techmasters)

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [x] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by MichelleRadu** [comment]
Hello Mudi!

At[ index.dev](url) have some available Software engineer (Backend) with strong relevant background. 
Would you like to receive 2-3 CVs?
