### ISSUE TITLE
[Context Labs] - [Senior Information Security Engineer] - [Hybrid/Cambridge MA] - [Salary not yet set] [USD]

### ISSUE THREAD

**Issue by MikeTheTA1** [TechnologyMasters/jobs#693]
Senior Information Security Engineer

Cambridge, MA or Hybrid

About this position:

You will be responsible for leading the implementation, maintenance, monitoring and management of information security solutions. The engineer delivers these solutions in accordance with the organization’s architectural designs, best practices, and regulatory or compliance requirements. As risks change, the security engineer is responsible for recommending modifications and enhancements to ensure the organization is evolving with the threat landscape.

 

The Senior Information Security Engineer contributes to the corporate security strategy with security leadership and other senior security staff, IT leaders and development engineers. Recipients of the engineer’s implementations and management include IT infrastructure, application development, security operations, security audit and other staff. Considered a highly knowledgeable individual, the senior security engineer is expected to lead the implementation, monitoring and management of information security solutions that address modern day threats, issues and risks.

This position reports directly to the Director, Security and Compliance.

In this role you will:

    Handle day-to-day implementation, monitoring and operational support of security solution hardware, software, managed solutions, and service provider relationships.
    Actively participate and lead security team meetings that facilitate secure design, implementation and operation.
    Engage in and lead information security projects that evaluate existing security infrastructure and propose changes as defined by security leadership and architects.
        Additionally, deliver projects on time, within budget and in accordance with service level agreements (SLAs).
    Assist with security incident response and system stability/availability issues as they occur.
        This may occasionally include involvement outside of regular work hours, and responsiveness is expected.
    Implement solutions observing compliance –Sarbanes-Oxley Act (SOX), SOC 2, ISO27000, and privacy laws.
    Work in tandem with architects, security analysts, risk/compliance analysts, incident responders, and development team members.
    Respond to and handle service and escalation tickets within SLA expectations.
    Research, validate and deploy solutions meeting security and business needs.
    Follow security engineering fundamentals and processes as defined in industry best practice documents.
    Influence the planning and execution of incident response and postmortem exercises, with a focus on creating measurable benchmarks to show progress (or deficiencies requiring additional attention).
    Focus on driving security efficiencies, enabling security team members to work on more advanced tasks.
    Anything else as may reasonably be required by the company

Experience:

    As a Highly technical and analytical professional, with a proven deep background in information technology design, implementation and delivery.
    Securing on premise networks and systems (extensive experience with this).
    Securing cloud computing technologies, including software, infrastructure and platform-as-a-service, as well as public, private, and hybrid environments.
    With traditional security controls and technologies (extensive experience with this).
        Such as Security Information and Event Management (SIEM) systems, intrusion detection/prevention systems (IDS/IPS), public key infrastructure (PKI), identity and access management (IDAM) systems, endpoint protection solutions including endpoint detection and response (EDR), threat intelligence platforms, 802.1X/NAC, and application controls.
    With vulnerability assessment and penetration testing requirements.
    Managing or using threat intelligence platforms, IDS/IPS, file integrity monitoring (FIM), data loss prevention (DLP) and other network and system monitoring tools.
    With privileged access management applications.
    With firewall policy creation, maintenance and analysis.
    With security automation solutions, especially for firewall policies.
    With Amazon Web Services (AWS).
    With one or more of the following: ISO 27001, NIST, SOX, the General Data Protection Regulation (GDPR), Center for Internet Security (CIS) standards or Service Organization Controls (SOC) 2.
    Working knowledge of Linux, Unix, and network device operating systems.
    Communicating business risk from cybersecurity issues.
    Working collaboratively in a matrixed team environment
    Excellent interpersonal skills with the ability to interface with all levels of the organization
    Ability to think strategically and tactically, with effective decision-making skills

Preferred Experience:

    10+ years’ experience in cybersecurity and risk management with a system and/or network security engineering background.
    Proficient with scripting in Python, JavaScript, PowerShell, PHP or Ruby.
    Holds or working toward one or more of the following certifications: SANS GIAC, CCSP, or CISSP.

Why you’ll like it here:

    Context Labs is collaborative at its core. You’ll work within your team and across the organization allowing for continuous learning and discovery.
    We set goals that matter and provide value in all that we do, from building meaningful products to positively impacting carbon reduction and climate change.
    Context Labs’ mission is to transform complex data into continuously proven information. Powered by Immutably™, an innovative, trusted data fabric platform, our integrated solutions deliver context-driven insights that enable human networks to spot patterns, correlate trends - and reveal the ground truth hidden inside the world’s most complicated, persistent problems.

We understand that applying for a job can be intimidating. Applicants rarely meet every single job requirement, and we know there are many skills and backgrounds that will contribute to success in this role. If you’re interested in applying, please do so.

Context Labs embraces diversity and equal opportunity. We are committed to building a team that represents a variety of backgrounds, perspectives, and skills. We believe the more inclusive we are, the better our products will be. Context Labs will ensure that individuals with disabilities are provided reasonable accommodation to participate in the job application or interview process, perform essential job functions, and receive other benefits and privileges of employment. If you require accommodation, please contact Erica Mackoff at HR@contextlabs.com.

 

Who we are:

Context Labs solves big global problems by elevating trust in data. Our Immutably™ Platform solutions enable individuals, companies, and governments to produce data-driven insights that can be irrefutably trusted and verified. While the technology has broad application, our main focus is on climate initiatives that move the needle.We're a rapidly growing team of creative problem-solvers that leverage disruptive technology to crack the world's fundamental “too hard” challenges (such as decarbonization and water/food security). Do you want to have an impact working with smart, passionate people that push themselves, support each other and celebrate wins as a team? Join us.

Job Link https://contextlabs.bamboohr.com/careers/97?source=aWQ9NDA%3D

**Comment by theetrain** [comment]
All job posts must include a salary. We can reopen this post once the title is updated.

**Comment by MikeTheTA1** [comment]
> 
Leadership hasn't set a salary range.
