### ISSUE TITLE
Backend Software Developers Needed

### ISSUE THREAD

**Issue by RenaeFarough** [TechnologyMasters/jobs#695]
I’m a founder of a generative Ai startup that is yet to be announced and on the hunt for solid software engineers. Specifically experienced backend developers with strong TypeScript skills, particularly Nest.js (Node.js also acceptable). Contract work is an option.

**Comment by thamilton-vs** [comment]
Hi, Renae
I would like to learn more details.
You can reach out to me on Linkedin - https://www.linkedin.com/in/trah/

**Comment by coolidev** [comment]
> Hi. Looking for a Back-end developer?
> Can you share further details with me?
> Please reach me at https://www.linkedin.com/in/jgoodidea
> Thanks.

**Comment by EzikeChris** [comment]
how do we apply

**Comment by brett-baker-dev** [comment]
Hello, Renae
I would like to learn more about this opportunity.
My linkedin profile is https://www.linkedin.com/in/brett-a-baker-dev/
Thank you.

**Comment by VoV40k** [comment]
I would be glad to suggest an awesome candidate. Please connect me: https://www.linkedin.com/in/vladimir-smirnov-litslink/

**Comment by fullstack412** [comment]
Send me a LinkedIn note! https://www.linkedin.com/in/eric-lee-9290b1219/

**Comment by RenaeFarough** [comment]
> Send me a LinkedIn note! https://www.linkedin.com/in/renaefarough/

Send me a LinkedIn note! https://www.linkedin.com/in/renaefarough/

**Comment by RenaeFarough** [comment]
> I'd like to learn more about this position

Send me a LinkedIn note! https://www.linkedin.com/in/renaefarough/

**Comment by nicetech-creator** [comment]
May we discuss details? https://www.linkedin.com/in/hanyangxu/

**Comment by jamie088** [comment]
> > I'd like to learn more about this position
> 
> Send me a LinkedIn note! https://www.linkedin.com/in/renaefarough/

just sent connection request in linkedin. please accept me.

**Comment by suzukidavid** [comment]
Hello, Renae
Do you need any software development?
Send me a message on Linkedin.
www.linkedin.com/in/suzukidavid
