### ISSUE TITLE
EnergyX Solutions - Ruby Developer - Toronto/ON Canada

### ISSUE THREAD

**Issue by ruanltbg** [TechnologyMasters/jobs#71]
### Salary Expectation

- $70K – $100K (annually)
-  Full Time
- 0.25% – 0.5%

### Benefits

- Startup environment.

### Location

- Toronto, Ontario

## What You'll Do _(Job Description)_

- Building and maintaining new features and functionality. 
- Building and maintaining automated tests for calculations 
- Customizing the platform for partners. 
- Communicating with engineering leadership about requirements.

### Must Have

- Self-starter attitude and good communication. 
- Experience and understanding working with OOP and MVC systems. 
- Ruby, SQL, HTML, CSS and Javascript (jQuery, etc).

### Nice to Have

- Vue.js
- You have experience with Bootstrap, PostgreSQL and Heroku/AWS. 
- You’ve worked with PHP or in MVC systems before.

### Relevant Experiences

- mobile technology
- User Interface design

## About Our company

My Energy Xpert is a simple online energy scan that is revolutionizing the building energy efficiency market by allowing anyone to complete a building energy scan online in around 15 minutes without costly professional assistance.

## How to apply
https://angel.co/energy-x/jobs/186316-rails-software-engineer
Please send an email to ruan@energyxsolutions.com with your resume, use 'Ruby Developer' as subject.

---

## Meta

- [X] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by walteraa** [comment]
@ruanltbg Does the company provide Visa Sponsorship?!

**Comment by ruanltbg** [comment]
Hi @walteraa, unfortunately no.
