### ISSUE TITLE
Visual Inclination - WordPress Developer -- GTA

### ISSUE THREAD

**Issue by gocamille** [TechnologyMasters/jobs#74]
# What You'll get
## Salary Expectation
- Negotiable
- Contract / Part-time

## Location
- Toronto, Ontario

## What You'll Do (Job Description)
Visual Inclination is looking for a contract/part-time developer to manage a Wordpress project over the next 8-10 months.  

### Must Have
- 2+ years working as a WordPress developer (PHP, HTML, CSS)

## About the Company:
Visual Inclination is a Toronto-based production company focused on full-service filmmaking, design, and web production.
https://www.visualinclination.com/

## How to apply
Please DM camille in TechMasters @camille

## Meta

- [ ]  Full Time
- [x] Part Time
- [x] Contract
- [ ]  Internship
- [ ]  Remote OK
- [ ]  Fully Remote
- [ ]  Hourly
- [ ]  Salary

**Comment by touchcatdigital** [comment]
@Camille @gocamille Andrew MacPherson (LinkedIn here): https://www.linkedin.com/in/amacph03/.  If this position is still available I would be more than happy to help.
