### ISSUE TITLE
The Richmond Group - Technical Co-Founder React Native Developer - UK, London

### ISSUE THREAD

**Issue by dreambesu** [TechnologyMasters/jobs#77]
**Technical Mobile App Developer Co-Founder** 

_The Richmond Group is an award winning investor and venture builder with a ground-breaking vision for the future. We started in 1999 around a kitchen table with a simple goal: to stop working in dead end jobs that we hated and do something meaningful. We have built several multi-million pound companies including a £1bn fin-tech lender in the UK. Having served over half a million customers and won many awards for being an amazing place to work, we are replicating our success into new geographies._

The Richmond Group are seeking an entrepreneurial, ambitious Technical Co-Founder to join our Edtech Incubator. The incubator is a space for great startups to develop with access to our very own vibrant working spaces, business mentors and investors (including the Richmond Group founder, James Benamor) and most importantly a brilliant and talented team of entrepreneurs. This is an exciting opportunity for a passionate developer to gain expertise in this area and once the business expands, be the CTO of the company. 

The successful candidate will be skilled in IOS or Android App development and responsible for all technology systems and infrastructure to implement the technology strategy of the business. You will be working in a fast paced environment alongside a small, competent team including a UX / UI designer and a product manager – working towards the MVP.

The ideal candidate will thrive on working on new disruptive products and will not be afraid to take calculated risks. You will have the chance to shape the company and the strategy alongside with guidance and direction from the company founder and team members.  

The following would be advantageous:

•	Experience managing your own projects
•	Experience as a mobile app developer
•	You can use any front-end 
•	You can use any back-end language 
	
### Benefits
•	Competitive salary package and equity.
•	Be one of the co-founders of an exciting business
•	Flexible workspace & hours - At Richmond Group there are no time sheets, we are paying for your results. We just ask that you keep your team members informed on when they can expect you to be available for communication and that you get the work done.

### Location

- London, Shoredtich
- Remote OK - UK only though

## How to apply

Please send an email to [recruitment@rgroup.co.uk] with your CV, use 'Technical Co-Founder' as subject

- [ ] Full Time
- [ ] Remote OK
- [ ] Salary

**Comment by theetrain** [comment]
Missing salary and job type details. Please use the 'Meta' checklist at the bottom of the template.
