### ISSUE TITLE
Full Stack Salesforce Developer -  Aurora, Ontario

### ISSUE THREAD

**Issue by TM240** [TechnologyMasters/jobs#78]
Issue title format: [Argus Software] - [Full Stack Salesforce Developer] - [Aurora, Ontario]

- Contract

### Benefits

Growth. The culture at Altus is one of fostering talent and recognizing potential. You will have every opportunity to extend and expand your skills and gain new ones. Whether you are an AngularJS expert or your front end coding needs updating; whether you are more comfortable in VisualForce and want to try out Lightning Components, this is a chance to extend your expertise and grow your career. 

Exposure. This is an opportunity to drive the end-to-end build on new Salesforce applications. This is a project at a global company and one that will make an impact on the work we are doing.

### Location

- Aurora, Ontario
- In office

## What You'll Do _(Job Description)_

Our Full Stack Salesforce Developer will:
- Develop and support. You will build custom applications in Force.com using classic Salesforce tools such a VisualForce as well as modern web technologies such as Lighting and AngularJS. You will participate in Salesforce OAuth or Bulk API.
- Collaborate. You will work with BA’s to collect and analyze business requirements.
- Develop. You will create new functionality for the application within SalesForce.
- Build out new functionality. You will work across the full stack to work on data-related and evaluation features and modules.
- Develop UIs. You will understand the needs of the system and how users will ingest information. You will build features that allow exporting of information and synchronization.
- Modify. You will convert existing code to Lighting Components.
- Build. You will use Process Builder to move existing and build new functionality within the application.
- Contribute to CI/CD. You will use Jenkins to compile and test your code and then trigger deployments in Octopus.
- Support. You will provide Operations support and application debugging where necessary.

### Qualifications
- An ideal combination of education and experience. You have a Bachelor’s degree in Computer Science. Salesforce Administrator and Developer Certifications are a bonus. You must have a minimum of 3 years of experience in Full Stack Salesforce development and deployment including custom page creation accessing external data sources and expertise performing the following:
- Configuration and release management using change sets in Salesforce.com and other deployment tools such as GIT and Jenkins.
- Monitoring and debugging running custom SFDC applications.
- Maintaining high security standards for all data stored in Salesforce.com.
- Architecting and building the data feeds, platform/environment configurations, ETLs and components needed to integrate Salesforce with external applications, data systems.  
- An expansive range of technical skills. You have proven experience with:
- Lightning Components or VisualForce.
- Advanced UI development using or Javascript tools such as AngularJS.
- The SFDC toolkit.
- Developing custom objects and workflow business rules including Process Builder.
- SQL and SOQL queries.
- Apex test classes and scripts.
- A creative problem solver. You can craft a solution using both custom development and purchased applications (solid knowledge and usage of AppExchange).
- A commitment to the Agile methodology. You have experience working in a SCRUM environment.
- A team oriented personality. You can easily build relationships and work closely with internal process teams, developers, users and management.
- An analytical mindset. You can quickly understand and analyze various approaches and processes instantly. You have the ability to drill down to the details, obtaining the right level of specificity.
- A winning communication style. You are concise, on point and effective. You can communicate technical details clearly to any level of audience.

## About Our company

Altus Group Limited is a leading provider of independent advisory services, software and data solutions to the global commercial real estate industry. Through our business lines, Altus Data Solutions, Altus Analytics and Altus Expert Services, we are creating innovative technology-enabled solutions that better enable the commercial real estate industry to analyze, gain market insight and recognize value on their investments. Our clients include some of the world’s largest real estate industry participants, spread across a broad variety of sectors.

## How to apply

Please apply through link: http://bit.ly/2HPkbuY

---

## Meta

- [ ] Full Time
- [ ] Part Time
- [x] Contract
- [ ] Internship
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by theetrain** [comment]
Please add company name, job details, and contact information as provided by the template: https://github.com/TechnologyMasters/jobs/blob/master/.github/issue_template.md
