### ISSUE TITLE
FrontApp - Node.js Developer - Paris

### ISSUE THREAD

**Issue by karolinaBT** [TechnologyMasters/jobs#83]
FrontApp - Node.js Developer - Paris
==============================================================
__About:__

At Front, we’re redefining business communication and collaboration with our shared inbox for teams. Front brings all of your communication channels (email, Facebook, Twitter, etc.) into one place, so you can triage and assign messages, have internal conversations around them, and even sync your work across other services you use from Salesforce to Github. Today, over 2,000 companies rely on Front, and we’re just getting started!

We are looking for an experienced Backend Engineer based in Paris to help build, manage, and scale the Front platform.

__What you'll do:__

*Design, develop, test and implement new product features: frontapp.com/roadmap
*Tune and optimize performance of the app, running on our new container infrastructure
*Improve the quality of our search
*Speed-up the analytics pipeline
*Build a service in charge of the synchronization with our email providers
*Re-implement some of our core components with a lambda architecture

__To be a good fit, you should have:__
*Fluent English skills
*Product mindset (we’re a product company on a mission to “advance how people work”)
*Fluency in a dynamic language like Javascript, Python, Ruby, or similar
*Track record of designing and implementing complex and scalable software services
*Experience architecting, deploying and operating asynchronous work queues, high-volume storage systems, and high-throughput systems
*Experience with performance benchmarking and diagnostic tools
*Understand the trade-offs in employing different engineering solutions to a problem, valuing pragmatism over idealism
*Ability to thrive in a dynamic, fast-paced, collaborative, and high-growth environment

__Bonus skills include:__
*Experience working with a multi-data center setup
*Extensive experience in node.js, MySQL and memcached on AWS
*Familiarity with email formats or intricate details of HTML parsing

__What can we offer you:__
* up to 60 K EUR/ Year if more than 3 years of experience, up to 75 K EUR / year if you have more than 5 years of experience,
*100% health care coverage with Alan
*50% of travel card
*60% of Ticket-restaurant / meal vouchers (meal vouchers = €9)
*Free breakfast on Monday
*Relocation package : 3000 € + 1 month Airbnb
*2 weeks on-boarding in SF
*Your own lego set: New team members build their own personal lego set.
*Last Macbooks and Bose noise-control headphones
*Free snacks and drinks

Additional info:
* Full-time, onsite, contract of employment

Interested? [Apply](https://bee.traffit.com/public/an/163)

**Comment by theetrain** [comment]
This post lacks salary information and labels from the 'meta' in the [issue template](https://github.com/TechnologyMasters/jobs/blob/master/.github/issue_template.md).
