### ISSUE TITLE
[FOR HIRE][REMOTE][CONTRACT] Full Stack Engineer - React/React Native/UX/Node/SQL/Redis/Elasticsearch/Docker.

### ISSUE THREAD

**Issue by ilovett** [TechnologyMasters/jobs#89]
[FOR HIRE][REMOTE][CONTRACT]
Full Stack Engineer specialized in React/React Native/UX/Node/SQL/Redis/Elasticsearch/Docker.   5 years professional experience with Single Page App Frameworks. 10 years professional experience JavaScript.   Able to provide UX Insights and Design using existing component libraries.

**Comment by theetrain** [comment]
Please follow the [template](https://github.com/TechnologyMasters/jobs/blob/master/.github/issue_template.md) when opening new job posts.

**Comment by matysanchez** [comment]
@ilovett can you tell more about the project?
