### ISSUE TITLE
Medior Web Developer - Creative Group - Amsterdam/Nijmegen 

### ISSUE THREAD

**Issue by YourConnector** [TechnologyMasters/jobs#94]
Do you want to contribute to the development of our high volume e-commerce platform? We are looking for a web developer to help us scale up using microservices and opensource software. Click here to see their roadmap and teck stack! 

Who we are:
Creative Group is the international e-commerce specialist for everything that is a code. No more buying your call credit, App store credit or e-tail credit in the supermarket or gasstation. By developing and operating various online platforms, we made selling, sending and  exchanging digital value easier, faster and globally! All so you have time to do what you áctually want to do.

Currently we handle over 15K orders on a daily basis worldwide and it’s growing at a rapid pace. Our platform needs to be ready to handle a tenfold volume increase. To achieve this we are migrating from a services oriented to a microservices architecture, moving our platform to the cloud and improving our test automation. We need your help with this.

What you will be doing:
- Work in self-organizing SCRUM teams of 5 (+/- 2) developers;
- Use (and improve upon) the open source technologies in our tech stack, such as Ruby, PHP, Vue.Js and Docker;
- Think with our commercial teams about new functionality;
- Build features for our customers.

This is your dream job if:
- You enjoy experimenting with new technologies;
- You like the challenges of a high volume platform;
- You take satisfaction in getting your ideas into production;
- You thrive in a fast-paced and constant changing environment;
- You bring 3 or more (5 senior) years of work experience that includes solid experience with web development, open source software and automated testing;
- Experience within an e-commerce environment is highly appreciated.

What we offer:
- A job in an e-commerce company with a start-up culture, 60 motivated people working on conquering the global e-value market;
- We focus on personal development; you have the possibility to learn new technologies, visit conferences/trainings and take part in guilds;
- Learn Ruby on Rails on the job;
- Company activities, such as hackathons, inspirational (tech) talks, teambuilding activities and monthly drinks;
- Remuneration consisting of salary, pension allowance, travel expenses, up to 29 paid leave days, a MacBook Pro and more company benefits;
- Working in Amsterdam and/or Nijmegen, it’s up to you. Working one day per week remote from your home is also negotiable.
- Free lunch in our own lunch bistro.

**Comment by YourConnector** [comment]
Be part of the Creative Group! http://yourconnector.nl/vacature/medior-web-developer/
Excited? We would be thrilled if you would apply! You can apply by clicking the apply button beneath, sending your motivation and CV/LinkedIn. Within 2 working days you will receive feedback if we think you match the job profile.
Our interview process consists of two rounds. During these rounds you will get to know the team, we will tell you everything about the adventures we have embarked on with Creative Group and you can ask all the questions you have.

**Comment by theetrain** [comment]
Please follow the [issue template](https://github.com/TechnologyMasters/jobs/blob/master/.github/issue_template.md) - a higher-quality post will yield higher engagement for you.
